bcgov/moh-keycloak-client-configurations

.github/workflows/terraform.yml, keycloak-prod/main.tf, keycloak-prod/realms/moh-applications/newclient.tf, keycloak-prod/variables.tf, main.tf, variables.tf
Also delete PROD NEWCLIENT (test client).
=> Create folder structure to manage PROD.

keycloak-dev/realms/moh-applications/miwt.tf, modules/payara-client/main.tf
added an output to the payara-client module
=> Added MIWT client (dev)

keycloak-dev/realms/moh-applications/pidp-service.tf
Create mapper on PIDP-SERVICE, not UMS.
=> Fix PIDP-SERVICE_ums_view-client-uci-sso_client_role_mapper

keycloak-dev/realms/moh_applications/pidp-service/main.tf, keycloak-dev/realms/moh_applications/user-management-service/main.tf, keycloak-dev/realms/moh_applications/user-management/main.tf, keycloak-prod/realms/moh_applications/pidp-service/main.tf, keycloak-prod/realms/moh_applications/user-management-service/main.tf, keycloak-prod/realms/moh_applications/user-management/main.tf, keycloak-test/realms/moh_applications/main.tf, keycloak-test/realms/moh_applications/pidp-service/main.tf, keycloak-test/realms/moh_applications/uci-sso/main.tf, keycloak-test/realms/moh_applications/uci-sso/outputs.tf, keycloak-test/realms/moh_applications/uci-sso/versions.tf, keycloak-test/realms/moh_applications/user-management-service/main.tf, keycloak-test/realms/moh_applications/user-management/main.tf
AB#7567: Adding view clients to PIdP Management groups in Keycloak Dev/Test
AB#7576: Adding UCI client to Keycloak Test
Alphabetizing UMS configs; Formatting
=> AB#7567-PIdP-UCI

.github/workflows/terraform.yml
Add `-recursive` to existing Terraform Format step
=> Add -recursive to existing Terraform Format step

keycloak-test/realms/moh_applications/main.tf, keycloak-test/realms/moh_applications/plr_conf/main.tf, keycloak-test/realms/moh_applications/plr_flvr/main.tf, keycloak-test/realms/moh_applications/plr_flvr/variables.tf, keycloak-test/realms/moh_applications/plr_iat/main.tf, keycloak-test/realms/moh_applications/plr_iat/variables.tf, keycloak-test/realms/moh_applications/plr_rev/main.tf, keycloak-test/realms/moh_applications/plr_rev/variables.tf, keycloak-test/realms/moh_applications/plr_sit/main.tf, keycloak-test/realms/moh_applications/plr_sit/variables.tf, keycloak-test/realms/moh_applications/plr_stg/main.tf, keycloak-test/realms/moh_applications/plr_stg/variables.tf, keycloak-test/realms/moh_applications/plr_uat/main.tf, keycloak-test/realms/moh_applications/plr_uat/variables.tf
Updated remaining test PLR clients with service account / default scopes / roles / mappers
=> Plr test env client updates

keycloak-dev/realms/moh_applications/user-management/main.tf, keycloak-prod/realms/moh_applications/user-management/main.tf, keycloak-test/realms/moh_applications/user-management/main.tf
Forgot that full path default setting is true. Which messes up the frontend I wrote
=> full path fix

keycloak-dev/realms/moh_applications/mspdirect-service/main.tf, keycloak-dev/realms/moh_applications/mspdirect-web/main.tf, keycloak-prod/realms/moh_applications/mspdirect-service/main.tf, keycloak-prod/realms/moh_applications/mspdirect-web/main.tf, keycloak-test/realms/moh_applications/mspdirect-service-uat/main.tf, keycloak-test/realms/moh_applications/mspdirect-service/main.tf, keycloak-test/realms/moh_applications/mspdirect-web-uat/main.tf, keycloak-test/realms/moh_applications/mspdirect-web/main.tf
In dev:
•       Add role MANAGEMSPPAYEENUMBER to MSPDIRECT-SERVICE 
•	Add role AUDITUSER to MSPDIRECT-SERVICE 
•	Add role MSPDIRECT-SERVICE/AUDITUSER to MSPDIRECT-WEB Scope Mappings 
In test:
•       Add role MANAGEMSPPAYEENUMBER to MSPDIRECT-SERVICE 
•	Add role AUDITUSER to MSPDIRECT-SERVICE 
•       Add role MANAGEMSPPAYEENUMBER to MSPDIRECT-SERVICE-UAT 
•	Add role AUDITUSER to MSPDIRECT-SERVICE-UAT 
•	Add role MSPDIRECT-SERVICE/AUDITUSER to MSPDIRECT-WEB Scope Mappings 
•	Add role MSPDIRECT-SERVICE-UAT/AUDITUSER to MSPDIRECT-WEB-UAT Scope Mappings 
In prod:
•	Add role AUDITUSER to MSPDIRECT-SERVICE 
•	Add role MSPDIRECT-SERVICE/AUDITUSER to MSPDIRECT-WEB Scope Mappings 
•	Add role MANAGEMSPPAYEENUMBER to MSPDIRECT-SERVICE
=> add new msp roles

keycloak-dev/realms/moh_applications/pidp-service/main.tf, keycloak-prod/realms/moh_applications/pidp-service/main.tf, keycloak-test/realms/moh_applications/pidp-service/main.tf
On October 24th on RocketChat, James Hollinger requested a new role to be added to DEV, TEST, and PROD.
=> Add role to PIDP-SERVICE. Role view_endorsement_data.

keycloak-dev/realms/moh_applications/user-management-service/main.tf, keycloak-dev/realms/moh_applications/user-management/main.tf
=> Add view-client-prp-service role to UMS

keycloak-test/realms/moh_applications/primary-care/main.tf
Request was to replace roles, hence the deletions in terraform plan
=> replace roles primary care on test

.github/workflows/terraform.yml, main.tf
=> specify terraform version in main.tf

keycloak-dev/realms/moh_applications/prp-service/main.tf, keycloak-dev/realms/moh_applications/prp-web/main.tf, keycloak-test/realms/moh_applications/prp-service/main.tf, keycloak-test/realms/moh_applications/prp-web/main.tf
Can you add the following roles to PRP-SERVICE in Dev and Test
•	PHYSICIAN
•	PHARMACIST
These should also be included in the PRP-WEB scope mappings
And remove ADMIN please. MSPQI and PMP will remain as is.
=> PRP dev test roles updates

keycloak-dev/realms/moh_applications/main.tf, keycloak-dev/realms/moh_applications/terraform/main.tf, keycloak-dev/realms/moh_applications/terraform/outputs.tf, keycloak-dev/realms/moh_applications/terraform/variables.tf, keycloak-dev/realms/moh_applications/terraform/versions.tf
Import terraform client on dev env.
Disable full_scope_allowed
Assign specified roles to Service account to manage clients within realm
=> import terraform client and specify service account roles

keycloak-test/realms/moh_applications/prime-application-local/main.tf, keycloak-test/realms/moh_applications/prime-application-local/outputs.tf, keycloak-test/realms/moh_applications/user-management-service/main.tf
Add PRIME-APPLICATION-LOCAL roles. Add view-prime-application-local to UMS in preparation for UMC access.
=> Add PRIME-APPLICATION-LOCAL roles

keycloak-dev/realms/moh_applications/terraform/main.tf
`Manage Realm` role will be deleted manually from KC Admin console after merging this PR
=> add realm-level roles to terraform client

keycloak-test/realms/moh_applications/main.tf, keycloak-test/realms/moh_applications/plr_aglstg/main.tf, keycloak-test/realms/moh_applications/plr_aglstg/outputs.tf, keycloak-test/realms/moh_applications/plr_aglstg/variables.tf, keycloak-test/realms/moh_applications/plr_aglstg/versions.tf, keycloak-test/realms/moh_applications/user-management-service/main.tf
=> create plr_aglstg client

keycloak-dev/realms/moh_applications/dmft-service/main.tf, keycloak-dev/realms/moh_applications/dmft-service/variables.tf, keycloak-dev/realms/moh_applications/main.tf, keycloak-test/realms/moh_applications/dmft-service/main.tf, keycloak-test/realms/moh_applications/dmft-service/outputs.tf, keycloak-test/realms/moh_applications/dmft-service/variables.tf, keycloak-test/realms/moh_applications/dmft-service/versions.tf, keycloak-test/realms/moh_applications/dmft-webapp/main.tf, keycloak-test/realms/moh_applications/dmft-webapp/outputs.tf, keycloak-test/realms/moh_applications/dmft-webapp/variables.tf, keycloak-test/realms/moh_applications/dmft-webapp/versions.tf, keycloak-test/realms/moh_applications/main.tf, keycloak-test/realms/moh_applications/user-management-service/main.tf
LICENSE-STATUS that dmft references was already created on test environment
=> create dmft clients and ums role

keycloak-test/realms/moh_applications/hcap-fe/main.tf
=> Add valid redirects to HCAP-FE in TEST

keycloak-test/realms/moh_applications/pidp-webapp/main.tf
copy of https://github.com/bcgov/moh-keycloak-client-configurations/pull/186/files
per James Hollinger request
=> add redirect uris for pidp

keycloak-dev/realms/moh_applications/user-management-service/main.tf
Deleted client -roles and client service-account-roles
=> Updated user-management-service

keycloak-dev/realms/moh_applications/dmft-webapp/main.tf, keycloak-prod/realms/moh_applications/dmft-service/main.tf, keycloak-prod/realms/moh_applications/dmft-service/outputs.tf, keycloak-prod/realms/moh_applications/dmft-service/variables.tf, keycloak-prod/realms/moh_applications/dmft-service/versions.tf, keycloak-prod/realms/moh_applications/dmft-webapp/main.tf, keycloak-prod/realms/moh_applications/dmft-webapp/outputs.tf, keycloak-prod/realms/moh_applications/dmft-webapp/variables.tf, keycloak-prod/realms/moh_applications/dmft-webapp/versions.tf, keycloak-prod/realms/moh_applications/licence-status/main.tf, keycloak-prod/realms/moh_applications/licence-status/outputs.tf, keycloak-prod/realms/moh_applications/licence-status/versions.tf, keycloak-prod/realms/moh_applications/main.tf, keycloak-test/realms/moh_applications/dmft-webapp/main.tf
Added dmft-service and dmft-webapp
=> Added DMFT client for PROD

keycloak-prod/realms/moh_applications/dmft-service/main.tf
Deleted Client host, id and address
=> Fixed terraform validation error for newly created client in prod

keycloak-test/realms/moh_applications/hcim_viha/main.tf, keycloak-test/realms/moh_applications/hcim_viha/outputs.tf, keycloak-test/realms/moh_applications/hcim_viha/versions.tf, keycloak-test/realms/moh_applications/main.tf
hcim_hd3 mapper will be created manually
=> create hcim_viha client on test

keycloak-dev/realms/moh_applications/licence-status/main.tf, keycloak-prod/realms/moh_applications/licence-status/main.tf, keycloak-test/realms/moh_applications/licence-status/main.tf
Add roles MD and RNP to license-status clients DEV-TEST-PROD
Add new roles
 
=> Add roles MD and RNP to license-status clients DEV-TEST-PROD

keycloak-dev/realms/moh_applications/dmft-webapp/main.tf, keycloak-test/realms/moh_applications/dmft-webapp/main.tf
Added redirect uri for dmft-webapp
Requested by Stanley on teams
 
=> Added redirect uri for dev

.github/pull_request_template.md
PR template updates: adding one bullet-point to checklist, and notes to document terraform configuration process.
=> Update PR template checklist

keycloak-test/realms/moh_applications/main.tf, keycloak-test/realms/moh_applications/tpl/main.tf, keycloak-test/realms/moh_applications/tpl/outputs.tf, keycloak-test/realms/moh_applications/tpl/versions.tf
Added config for TPL client onboarding for test env
Added maint.tf
Added Outputs.tf
Added variables.tf'
Added versions.tf
Added module maint.tf in root folder
Client onboarding request
https://dev.azure.com/cgi-vic-hlth/AM%20Team/_workitems/recentlyupdated/
 
=> Tpl client onboarding

keycloak-test/realms/moh_applications/tpl/main.tf, keycloak-test/realms/moh_applications/user-management-service/main.tf, keycloak-test/realms/moh_applications/user-management/main.tf
Added view-client-tpl role for UMS
Grant  UMC access to TPL admin
 
=> Added view-cllient-tpl role for UMS

keycloak-test/realms/moh_applications/tpl/main.tf
Updated default scopes
Updated main.tf. Added requested scopes
Client request to add missing default scopes (profiles, roles, web-origins)
 
=> Updated main.tf

keycloak-prod/realms/moh_applications/clients/user-management/main.tf
Add a scope mapping for UMC to get UMS primary care roles.
This change allows UMC to manage Primary Care roles.
=> USER-MANAGEMENT PROD: Scope mapping for Primary Care.

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-prod/realms/moh_applications/clients/user-management-service/main.tf, keycloak-prod/realms/moh_applications/clients/user-management/main.tf
HSPP updates for prod config including:
- adding UMC access
- adding a mapper to display idir_displayName for username
HSPP require these changes to allow them to use and manage the app in prod
 
=> Hssp prod updates

keycloak-test/realms/moh_applications/clients.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/outputs.tf, keycloak-test/realms/moh_applications/clients/hspp/versions.tf
HSPP application is being added to the test environment
The application is required for testing
 
=> HSPP add application in test env

keycloak-test/realms/moh_applications/clients/hspp/main.tf
Hspp - updating test redirects URLs
The application URL has changed in test so the redirect needs to be updated.
 
=> Hspp update test redirects

keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding roles for HSPP client on test env and ordering the existing ones.
 
=> add hspp toles to test env

keycloak-dev/realms/moh_applications/clients.tf, keycloak-dev/realms/moh_applications/clients/forms/main.tf, keycloak-dev/realms/moh_applications/clients/forms/outputs.tf, keycloak-dev/realms/moh_applications/clients/forms/versions.tf, keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/forms/main.tf, keycloak-prod/realms/moh_applications/clients/forms/outputs.tf, keycloak-prod/realms/moh_applications/clients/forms/versions.tf
Adding new FORMS Dev + Prod clients for Keycloak Dev + Prod. Updating FORMS Test client in Keycloak Test.
FORMS is a Drupal application looking to be onboarded in an expedited manner. See [AB#10457 - Add Dev FORMS client configuration to Keycloak Dev](https://dev.azure.com/cgi-vic-hlth/AM%20Team/_workitems/edit/10457), [AB#10435 - Add Test FORMS client configuration to Keycloak Test](https://dev.azure.com/cgi-vic-hlth/AM%20Team/_workitems/edit/10435), and [AB#10436 - Add Prod FORMS client configuration to Keycloak Prod](https://dev.azure.com/cgi-vic-hlth/AM%20Team/_workitems/edit/10436) for more details.
 
[^1]: Data transparency. Does the client you are creating have the permissions to pass/access all the Client Scope attributes in the token? For example `profile` scope includes user …
=> Adding FORMS Dev + Prod clients; Updating FORMS Test client

keycloak-test/realms/moh_applications/clients/primary-care/main.tf
PRIMARY-CARE in TEST: Add new redirects at request of Jared Penner.
Jared Penner has requested an urgent change for the test environment in support of an interim release.
=> PRIMARY-CARE in TEST: Add new redirects at request of Jared Penner.

keycloak-test/realms/moh_applications/clients/pidp-service/main.tf, keycloak-test/realms/moh_applications/clients/pidp-webapp/main.tf
Adding birthdate mapper for PIDP on Test environment.
=> add birthdate mapper to pidp

keycloak-prod/realms/moh_applications/clients/ppm-api-cgi-BC30550160/main.tf
Updated client config attributes
=> Updated client config attributes

keycloak-test/realms/moh_applications/clients/dhiper/main.tf
Adding HI_Administrator role to DHIPER client on Test env.
=> add-dhiper-admin-role

keycloak-test/realms/moh_applications/clients/prp-service/main.tf, keycloak-test/realms/moh_applications/clients/prp-web/main.tf
Changing PRP roles names on Test environment. 
Renaming to follow the new architecture naming convention. As per Joyce request.
=> remove uppercase notation from prp test roles

keycloak-prod/realms/moh_applications/clients/sat-eforms/main.tf, keycloak-test/realms/moh_applications/clients/sat-eforms/main.tf
Renaming SAT-EFORMS role
Request from James Hollinger
=> rename phsa_eforms_immsbc role

keycloak-prod/realms/moh_applications/clients/ppm-api-cgi-BC30550160/main.tf
Updated mapper to required format
The PPM CGI client requires Pharmanet audience
=> Updated mapper to required format

keycloak-test/realms/moh_applications/clients/lra-dev/main.tf, keycloak-test/realms/moh_applications/clients/lra-sandbox/main.tf, keycloak-test/realms/moh_applications/clients/lra-test/main.tf
Adding Redirect URLs for LRA clients on Test env.
=> add LRA redirect uris

keycloak-prod/realms/moh_applications/groups.tf, keycloak-prod/realms/moh_applications/groups/prp-user-admin/main.tf, keycloak-prod/realms/moh_applications/groups/prp-user-admin/output.tf, keycloak-prod/realms/moh_applications/groups/prp-user-admin/variables.tf, keycloak-prod/realms/moh_applications/groups/prp-user-admin/versions.tf
Creating PRP admin group
The group will allow to manage PRP users and roles through UMC
=> crete prp management group

keycloak-test/realms/moh_applications/clients/dhiper/main.tf
Adding valid redirect URI to DHPER client on test env.
=> add dhiper redirect url

keycloak-dev/realms/moh_applications/clients/pho-rsc/main.tf
Updating PHO-RSC dev roles.
Mailbox request.
=> updade pho-rsc dev roles

keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Adding new redirect URL for PRIMARY-CARE client on Keycloak Test Environment.
AM Team mailbox request. Primary Care is doing UAT testing.
=> add primary-care redirect URI

keycloak-dev/realms/moh_applications/clients/moh-splunk-copy/main.tf
=> Changing protocol mapper to SAML variant

keycloak-test/realms/moh_applications/clients.tf, keycloak-test/realms/moh_applications/clients/plr-wava/main.tf, keycloak-test/realms/moh_applications/clients/plr-wava/variables.tf
Added: 
- PLR_IAT service client with required roles 
- Set the token lifespan timeout
Additional service account roles were required for testing along with a longer timeout.
=> Plr wava test updates

keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding redirect URL for HSPP on test env.
Mailbox request from Joyce
=> add redirect url for hspp

keycloak-prod/realms/moh_applications/clients/tbcm/main.tf
adding TBCM roles to /userinfo endpoint on Prod environment
=> create tbcm prod role mapper

.github/workflows/zap-scan.yml
Add ZAP Scan GitHub Action to scan our Common-Logon (Keycloak) environments.
Baseline ZAP scan results are required before remediating Content Security Policy (CSP) related issues on the shared Common-Logon page.
=> AB#10644 - Remediation for Keycloak based on AWS Zap Scan

keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Add redirect uri for primary-care test client
=> add redirect uri for primary-care on test

keycloak-test/realms/moh_applications/clients/icy/main.tf, keycloak-test/realms/moh_applications/groups.tf, keycloak-test/realms/moh_applications/groups/icy-management/main.tf, keycloak-test/realms/moh_applications/groups/icy-management/output.tf, keycloak-test/realms/moh_applications/groups/icy-management/variables.tf, keycloak-test/realms/moh_applications/groups/icy-management/versions.tf
Fix ICY description - previous one was longer than 255 chars. Add ICY management group.
=> Fix icy description add management group

keycloak-test/realms/moh_applications/clients/sa-sfdc/main.tf
Add redirect URL to allow SAT QA environment
=> add redirect url to sa-sfdc test

keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Adding redirect URLs for PRIMARY-CARE
=> add primary-care redirect uris

keycloak-test/realms/moh_applications/clients/hspp/main.tf
Add redirect URL to HSPP test instance.
=> add-hspp-redirect-url

keycloak-dev/realms/moh_applications/clients/pho-rsc/main.tf, keycloak-prod/realms/moh_applications/clients/pho-rsc/main.tf
Adding roles to PHO-RSC dev and prod clients as per David Arnatt's request.
=> create pho-rsc roles

keycloak-dev/realms/moh_applications/clients/pho-rsc/main.tf, keycloak-prod/realms/moh_applications/clients/pho-rsc/main.tf
Changing the role names.
Typo in client request.
=> fix role name typo

keycloak-prod/realms/moh_applications/clients/pho-rsc/main.tf
Updating PHO-RSC client roles on Production environment to match Dev env. 
Request from Brandon May. The roles being deleted are not consumed by any users on Production env.
=> update pho-rsc prod roles

keycloak-prod/realms/moh_applications/clients/sat-eforms/main.tf, keycloak-test/realms/moh_applications/clients/sat-eforms/main.tf
Adding a new role for the SAT-EFORMS client on Test and Production environment.
=> add eforms role test prod

keycloak-test/realms/moh_applications/clients.tf, keycloak-test/realms/moh_applications/clients/alr/main.tf, keycloak-test/realms/moh_applications/clients/alr/outputs.tf, keycloak-test/realms/moh_applications/clients/alr/versions.tf
Creating ALR client on Keycloak test environment. 
ALR is a Salesforce application. Roles will be added to the client, once finalized.
=> create test ALR client

keycloak-test/realms/moh_applications/clients/alr/main.tf
=> add ALR redirect urls

keycloak-test/realms/moh_applications/clients/alr/main.tf
Creating roles and mapper for ALR
Some resources were created manually during troubleshooting, Those resources will be deleted before running the  `apply` step
=> create ALR roles and mapper

keycloak-dev/realms/moh_applications/clients/hcimweb/main.tf, keycloak-dev/realms/moh_applications/clients/hcimweb_hd2/main.tf
Updating explicitly defined themes for HCIMWEB clients on dev. The update was done manually, so terraform should not show those changes
=> update dev bcsc themes

keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/icy/main.tf, keycloak-prod/realms/moh_applications/clients/icy/outputs.tf, keycloak-prod/realms/moh_applications/clients/icy/versions.tf, keycloak-prod/realms/moh_applications/clients/user-management-service/main.tf, keycloak-prod/realms/moh_applications/clients/user-management/main.tf, keycloak-prod/realms/moh_applications/groups.tf, keycloak-prod/realms/moh_applications/groups/icy-management/main.tf, keycloak-prod/realms/moh_applications/groups/icy-management/output.tf, keycloak-prod/realms/moh_applications/groups/icy-management/variables.tf, keycloak-prod/realms/moh_applications/groups/icy-management/versions.tf
Promoting ICY client to Production. Creating management group.
Client is an exact copy of Test ICY
=> create icy client on prod

keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/plr-prp/main.tf, keycloak-prod/realms/moh_applications/clients/plr-prp/outputs.tf, keycloak-prod/realms/moh_applications/clients/plr-prp/variables.tf, keycloak-prod/realms/moh_applications/clients/plr-prp/versions.tf, keycloak-test/realms/moh_applications/clients/plr-prp/main.tf
Updated the Organization for PLR-PRP on test. Create PLR-PRP client on Production environment.
Service account that allows PRP to call PLR API.
=> configure plr-prp client

keycloak-prod/realms/moh_applications/clients/alr/main.tf, keycloak-test/realms/moh_applications/clients/alr/main.tf
Adding new role for ALR on Test and Production env.
=> add ALR role

keycloak-prod/realms/moh_applications/groups/icy-management/main.tf, keycloak-test/realms/moh_applications/groups/icy-management/main.tf
Assigning manage-user-details permissions to ICY group. Making config Consistent in test and Prod
=> add permissions to icy-management

keycloak-prod/realms/moh_applications/groups/itsb-access-team/main.tf
Edit ITSB-Access-Team permissions to include view-client-icy
ICY went to Prod and ITSB is responsible for user management of this app.
=> update itsb permissions

keycloak-test/realms/moh_applications/clients/edrd/main.tf, keycloak-test/realms/moh_applications/clients/usam/main.tf
Adding redirect URLs to different EDRD environments. Adding USAM redirect URL
=> update edrd redirect urls

keycloak-test/realms/moh_applications/clients/usam/main.tf
=> add usam redirect url

keycloak-prod/realms/moh_applications/clients/alr/main.tf, keycloak-test/realms/moh_applications/clients/usam/main.tf
Adding new redirect to ALR on Production. Updating USAM redirect to `https`
=> update alr and usam redirects

keycloak-test/realms/moh_applications/clients/edrd/main.tf, keycloak-test/realms/moh_applications/clients/user-management-service/main.tf, keycloak-test/realms/moh_applications/clients/user-management/main.tf, keycloak-test/realms/moh_applications/groups.tf, keycloak-test/realms/moh_applications/groups/edrd-management/main.tf, keycloak-test/realms/moh_applications/groups/edrd-management/output.tf, keycloak-test/realms/moh_applications/groups/edrd-management/variables.tf, keycloak-test/realms/moh_applications/groups/edrd-management/versions.tf, keycloak-test/realms/moh_applications/realm-roles/manage-users/main.tf
Create EDRD-management group. Update EDRD roles.  Update UMS/UMC clients to include view-client-edrd. Update realm-level role that is assigned to CGI Dev team.
=> create edrd management group and update roles

keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Adding new redirect URLs for PRIMARY-CARE.
=> add primary-care-urls

keycloak-test/realms/moh_applications/clients/hspp/main.tf
Add new redirect URL to HSPP on test.
=> add redirect url to hspp

keycloak-test/realms/moh_applications/clients/alr/main.tf
=> add alr redirect

keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Adding new role from PRIMARY-CARE on Test
=> add primary care role

keycloak-test/realms/moh_applications/clients/alr/main.tf
Adding redirect URLs for ALR on test
=> update alr redirects

keycloak-test/realms/moh_applications/clients/alr/main.tf
Add ALR redirects for Test env. URLs were added manually as a part of troubleshooting - > tf plan should show no changes
=> add more alr urls

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding HSPP_Restricted_SAN role and ordering the entries alphabetically.
=> add hspp role and order entries alphabetically

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Add hspp role in Test and Prod
=> add hspp role

keycloak-prod/realms/moh_applications/clients/primary-care/main.tf
Adding role for PRIMARY-CARE on Production
=> update primary care prod roles

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding new role for HSPP - test + prod
=> add new hspp role

keycloak-dev/realms/moh_applications/clients/ums-integration-tests/main.tf, keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/plr-lra/main.tf, keycloak-prod/realms/moh_applications/clients/plr-lra/outputs.tf, keycloak-prod/realms/moh_applications/clients/plr-lra/variables.tf, keycloak-prod/realms/moh_applications/clients/plr-lra/versions.tf
Moving PLR-LRA client to production. Copy of PLR-LRA client from test, with different organization assigned. Service account.
+ Persisting description changes on UMS-INTEGRATION-TESTS client
=> Create plr lra client

keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/hcim_lra/main.tf, keycloak-prod/realms/moh_applications/clients/hcim_lra/outputs.tf, keycloak-prod/realms/moh_applications/clients/hcim_lra/versions.tf
Moving HCIM-LRA client to Production. Exact copy of test client.
=> create hcim-lra client on prod

keycloak-test/realms/moh_applications/clients/alr/main.tf
Adding new redirect URLs for ALR client
=> add ALR redirects

keycloak-test/realms/moh_applications/clients.tf, keycloak-test/realms/moh_applications/clients/plr-cpsbc/main.tf, keycloak-test/realms/moh_applications/clients/plr-cpsbc/outputs.tf, keycloak-test/realms/moh_applications/clients/plr-cpsbc/variables.tf, keycloak-test/realms/moh_applications/clients/plr-cpsbc/versions.tf
Create PLR-CPSBC client in TEST for PLR-IAT APIs.
The College of Physicians and Surgeons asked to have access to a PLR environment so they can test and develop their FHIR messages against our FHIR maintain service.
=> Create PLR-CPSBC client in TEST for PLR-IAT APIs.

keycloak-test/realms/moh_applications/clients/phlat-web/main.tf
Adding redirect URL for PHLAT test environment
=> update phlat redirects

keycloak-test/realms/moh_applications/clients/edrd-portal/main.tf
Adding missing Scopes for EDRD-PORTAL client.
=> add missing scopes

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding 4 new roles for HSPP test and Production environments
=> add hspp roles

keycloak-test/realms/moh_applications/clients/plr-shoppers/main.tf
Update the PLR-SHOPPERS orgId.
Gary D. requested this change.
=> PLR-SHOPPERS TEST: Update orgId. Remove unneeded mappers.

keycloak-test/realms/moh_applications/clients/alr/main.tf
Add redirect to ALR client on TEST
ALR team wants to validate one more sandbox environment.
=> add redirect url

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Add HSPP_Restricted_BCCStat to HSPP for TEST and PROD
HSPP team requests a new role be added to TEST and PROD.
=> Add new HSPP role to TEST and PROD: HSPP_Restricted_BCCStat.

keycloak-test/realms/moh_applications/clients/hsiar/main.tf
Updating HSIAR redirects and description.
=> Update hsiar redirects

keycloak-prod/realms/moh_applications/groups/hsiar-management/main.tf, keycloak-test/realms/moh_applications/groups/hsiar-management/main.tf
Updating HSIAR Management group permissions
=> update hsiar management group permissions

keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/hcim_moh_crs/main.tf, keycloak-prod/realms/moh_applications/clients/hcim_moh_crs/outputs.tf, keycloak-prod/realms/moh_applications/clients/hcim_moh_crs/versions.tf
Create hcim_moh_crs service account in PROD.
Kim G. requests that TEST service account be copied to PROD.
=> Create hcim_moh_crs service account in PROD

keycloak-dev/realms/moh_applications/clients/pho-rsc-groups/main.tf, keycloak-dev/realms/moh_applications/groups.tf
Add PHO-RSC group for UMC management in DEV
Forgot to include in last PR.
=> Add PHO-RSC group for UMC management in DEV

keycloak-dev/realms/moh_applications/clients/user-management/main.tf
Add PHO-RSC-GROUPS to UMC client scope mappings
Forgot on previous PR.
=> Add PHO-RSC-GROUPS to UMC client scope mappings

keycloak-prod/realms/moh_applications/clients/hsiar/main.tf, keycloak-test/realms/moh_applications/clients/hsiar/main.tf
New roles for HSIAR in Test and Prod environments
=> create hsiar roles

keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/usam/main.tf, keycloak-prod/realms/moh_applications/clients/usam/outputs.tf, keycloak-prod/realms/moh_applications/clients/usam/versions.tf
Create USAM client on Production. Exact copy of Test client.
=> create USAM prod client

keycloak-test/realms/moh_applications/clients/hsiar/main.tf
Add redirect URL for HSIAR app on TEST env.
=> update hsiar urls

keycloak-prod/realms/moh_applications/clients/pho-rsc/main.tf
Renaming client on Production. Was not included in previous PR.
=> update client name on prod

keycloak-test/realms/moh_applications/clients/dmft-webapp/main.tf
Adding new redirect URLs for DMFT-WEBAPP client on Test environment.
Probably another PR will be required later in the day, to cleanup stale URLs
=> update dmft redirect urls

keycloak-dev/realms/moh_applications/groups/pho-rsc-management/main.tf, keycloak-prod/realms/moh_applications/groups/pho-rsc-management/main.tf
PHO-RSC Management group name change on dev and prod.
PHO-RSC rebranding to POSIT
=> update pho-rsc management group name

keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/hides/main.tf, keycloak-prod/realms/moh_applications/clients/hides/outputs.tf, keycloak-prod/realms/moh_applications/clients/hides/versions.tf, keycloak-test/realms/moh_applications/clients/hides/main.tf
Creating HIDES client configuration on Keycloak Prod env. Exact copy of Test client.
Updating HIDES Test client redirect URLs.
HIDES client onboarding
=> Create and update hides client

keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/hcim_fha_dfd/main.tf, keycloak-prod/realms/moh_applications/clients/hcim_fha_dfd/outputs.tf, keycloak-prod/realms/moh_applications/clients/hcim_fha_dfd/versions.tf
Promoting HCIM_FHA-DFD client to Production. Exact copy of the test client.
AM team mailbox request. Service account, so name not needed.
=> move hcim-fha-dfd client to production

keycloak-prod/realms/moh_applications/clients/hsiar/main.tf, keycloak-test/realms/moh_applications/clients/hsiar/main.tf
/adding new roles for HSIAR on test and prod
HSIAR client onboarding
=> create new hsiar roles

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Add HSPP roles on test and prod env.
Mailbox request.
=> create hspp roles

keycloak-prod/realms/moh_applications/clients/hsiar/main.tf, keycloak-test/realms/moh_applications/clients/hsiar/main.tf
Updating HSIAR role list on test and prod env.
HSIAR mailbox request
=> Update hsiar roles

keycloak-dev/realms/moh_applications/clients/forms/main.tf
Terraform test of keycloak_generic_client_protocol_mapper. Changing arbitrary attribute values.
=> Terraform test of keycloak_generic_client_protocol_mapper. Changing arbitrary attribute values.

keycloak-prod/realms/moh_applications/clients/hsiar/main.tf, keycloak-test/realms/moh_applications/clients/hsiar/main.tf
Removing deprecated roles from test and prod HSIAR configuration.
HSIAR request - preparing to move to Prod.
=> hsiar roles cleanup

keycloak-prod/realms/moh_applications/realm-roles/manage-users/main.tf, keycloak-test/realms/moh_applications/realm-roles/manage-users/main.tf
Add ums:view-metrics to MANAGE-USERS composite role in TEST and PROD.
NA
=> Add ums:view-metrics to MANAGE-USERS composite role in TEST and PROD.

keycloak-prod/realms/moh_applications/groups.tf, keycloak-prod/realms/moh_applications/groups/cgi-registries-admin/main.tf, keycloak-prod/realms/moh_applications/groups/cgi-registries-admin/output.tf, keycloak-prod/realms/moh_applications/groups/cgi-registries-admin/variables.tf, keycloak-prod/realms/moh_applications/groups/cgi-registries-admin/versions.tf, keycloak-test/realms/moh_applications/groups/registries-admin/main.tf
Create CGI Registries Admin Group in PROD. Add HCIM and PLR management permissions to group in TEST.
As requested by BSL.
=> Create CGI Registries Admin Group in PROD. 

keycloak-prod/realms/moh_applications/clients/icy/main.tf, keycloak-test/realms/moh_applications/clients/icy/main.tf
Add 32 ICY roles to TEST and PROD.
ISBINC0011180 - Keycloak/Salesforce ICY: Detailed Salesforce Role Hierarchy - Phase 3 Communities
=> Add 32 icy roles

keycloak-prod/realms/moh_applications/clients/hides/main.tf
Add redirect URLs to HIDES client
HIDES team request - testing production environment. Client onboarding
=> add redirect URLS to HIDES prod

keycloak-test/realms/moh_applications/clients/icy/main.tf, keycloak-test/realms/moh_applications/clients/maid/main.tf
Adding redirect URLs to MAID and ICY on Keycloak Test environment
CGI Salesforce team configured new environment.
=> update MAID and ICY urls

keycloak-test/realms/moh_applications/clients.tf, keycloak-test/realms/moh_applications/clients/edrd-portal/main.tf, keycloak-test/realms/moh_applications/clients/edrd-portal/variables.tf
Removing EDRD-PORTAL role and scope mappings
EDRD client onboarding
=> edrd-portal config cleanup

keycloak-dev/realms/moh_applications/clients/user-management-service/main.tf, keycloak-dev/realms/moh_applications/clients/user-management/main.tf, keycloak-test/realms/moh_applications/clients/edrd-portal/main.tf, keycloak-test/realms/moh_applications/clients/user-management-service/main.tf, keycloak-test/realms/moh_applications/clients/user-management/main.tf
EDRD-PORTAL client config update. Adding bulk-removal role to dev env.
=> Update edrd portal config

keycloak-test/realms/moh_applications/groups/edrd-management/main.tf, keycloak-test/realms/moh_applications/realm-roles/manage-users/main.tf
Updating group permissions so that EDRD-PORTAL is visible in UMC TEST
=> update edrd-portal umc permissions

keycloak-dev/realms/moh_applications/clients/ums-integration-tests/main.tf, keycloak-test/realms/moh_applications/clients/edrd/main.tf
Adding EDRD redirect URL and UMS-INTEGRATION-TESTS role.
=> update ums-integration-tests and edrd clients

keycloak-prod/realms/moh_applications/clients/hcimweb/main.tf, keycloak-prod/realms/moh_applications/clients/hcimweb_hs1/main.tf, keycloak-test/realms/moh_applications/clients/primary-care/main.tf
New redirect URL for PRIMARY-CARE
=> add redirect url for test primary-care

keycloak-test/realms/moh_applications/clients/edrd-portal/main.tf, keycloak-test/realms/moh_applications/clients/genesys-training/main.tf, keycloak-test/realms/moh_applications/clients/genesys/main.tf
Add redirect URL for EDRD-PORTAL client. Persist GENESYS custom theme changes.
=> update edrd and genesys config

keycloak-test/realms/moh_applications/clients.tf, keycloak-test/realms/moh_applications/clients/genesys-production/main.tf, keycloak-test/realms/moh_applications/clients/genesys-production/outputs.tf, keycloak-test/realms/moh_applications/clients/genesys-production/versions.tf
Creating a Genesys PROD client. 
Client will be moved from Keycloak Test to Production environment after testing is complete.
Exact copy of other genesys clients, with different organization name.
=> create temporary genesys client

keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Add PHR roles to PRIMARY-CARE client.
The PHSA PHR designers have approved this approach.
=> Add PHR roles to PRIMARY-CARE client.

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Add new role to HSPP on test and prod
=> add new roles to hspp client

keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/panorama/main.tf, keycloak-prod/realms/moh_applications/clients/panorama/outputs.tf, keycloak-prod/realms/moh_applications/clients/panorama/versions.tf
Create Panorama client in Prod. Same config as in Test env. Possibly more redirect URLs to come during the development/testing process.
=> create panorama prod client

keycloak-test/realms/moh_applications/clients/phlat_stg-service/main.tf
Change PHLAT org to numerical.
=> update phlat service org

keycloak-prod/realms/moh_applications/clients/genesys/main.tf, keycloak-test/realms/moh_applications/clients/genesys-training/main.tf, keycloak-test/realms/moh_applications/clients/genesys/main.tf
Removing custom claim that was used to redirect away from "splash" screen
Client request - decision changed on application landing page.
=> remove genesys custom claim and change base url

keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/hlbc/main.tf, keycloak-prod/realms/moh_applications/clients/hlbc/outputs.tf, keycloak-prod/realms/moh_applications/clients/hlbc/versions.tf
Promote the HLBC client to PROD.
Promotion requested by project team.
=> Promote the HLBC client to PROD.

keycloak-prod/realms/moh_applications/clients/hlbc/main.tf
HLBC PROD: Temporarily allow dev redirect URI.
Requested by HLBC team.
=> HLBC PROD: Temporarily allow dev redirect URI.

keycloak-test/realms/moh_applications/clients/primary-care/main.tf
New PRIMARY-CARE URL on Keycloak Test
=> add primary care url

keycloak-prod/realms/moh_applications/clients/primary-care/main.tf
Promoting PHR roles to Prod env
PHR client onboarding
=> add phr roles to prod primary-care

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Added HSPP_Restricted_DART role to both test and prod environments.
Support for HSPP client BCMOHAM-16328
=> added new role for HSPP in test and prod

keycloak-dev/realms/moh_citizen/clients/emaccs/main.tf, keycloak-dev/realms/moh_citizen/clients/emaccs/outputs.tf
EMACCS DEV was created in the wrong realm. Move to MOH_CITIZEN.
NA
=> EMACCS DEV was created in the wrong realm. Move to MOH_CITIZEN.

keycloak-test/main.tf, keycloak-test/realms/moh_citizen/clients.tf, keycloak-test/realms/moh_citizen/clients/emaccs/main.tf, keycloak-test/realms/moh_citizen/clients/emaccs/outputs.tf, keycloak-test/realms/moh_citizen/clients/emaccs/versions.tf, keycloak-test/realms/moh_citizen/versions.tf
Create the EMACCS client in the moh_citizen realm on TEST.
NA
=> Create the EMACCS client in the moh_citizen realm on TEST.

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Add new role HSPP_ReportSection_DART to both Prod and Test environment.
New role requested to be added by client.
=> add new hspp role to prod and test

keycloak-prod/realms/moh_applications/clients/alr/main.tf, keycloak-test/realms/moh_applications/clients/alr/main.tf
New roles for ALR on test and prod env. Cleanup empty description fields.
Client support request
=> create alr roles

keycloak-prod/realms/moh_applications/clients/edrd/main.tf, keycloak-test/realms/moh_applications/clients/edrd/main.tf
New role for EDRD on Test and Prod.
Request at the client meeting.
=> new edrd role

keycloak-prod/realms/moh_applications/clients/alr/main.tf, keycloak-test/realms/moh_applications/clients/alr/main.tf
Adding new role to ALR client on Test and Prod envs.
Client request
=> create alr role

keycloak-prod/realms/moh_applications/clients/user-management-service/main.tf, keycloak-prod/realms/moh_applications/clients/user-management/main.tf, keycloak-prod/realms/moh_applications/realm-roles/manage-users/main.tf, keycloak-test/realms/moh_applications/clients/user-management-service/main.tf, keycloak-test/realms/moh_applications/clients/user-management/main.tf, keycloak-test/realms/moh_applications/realm-roles/manage-users/main.tf
Add bulk-removal permissions to UMC/UMS and Manage Users realm role on Production and Test environments.
Part of bulk-removal feature work.
=> add bulk-removal permissions

keycloak-prod/realms/moh_applications/groups.tf, keycloak-prod/realms/moh_applications/groups/cgi-salesforce/main.tf, keycloak-prod/realms/moh_applications/groups/cgi-salesforce/output.tf, keycloak-prod/realms/moh_applications/groups/cgi-salesforce/variables.tf, keycloak-prod/realms/moh_applications/groups/cgi-salesforce/versions.tf
Create CGI Salesforce group in PROD. All ALR to group in TEST and PROD.
[BCMOHAM-19928](https://proactionca.ent.cgi.com/jira/browse/BCMOHAM-19928)
=> Create CGI Salesforce group in PROD. All ALR to group in TEST and PROD.

keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/edrd-portal/main.tf, keycloak-prod/realms/moh_applications/clients/edrd-portal/outputs.tf, keycloak-prod/realms/moh_applications/clients/edrd-portal/variables.tf, keycloak-prod/realms/moh_applications/clients/edrd-portal/versions.tf, keycloak-prod/realms/moh_applications/clients/user-management-service/main.tf, keycloak-prod/realms/moh_applications/clients/user-management/main.tf, keycloak-prod/realms/moh_applications/groups/edrd-management/main.tf, keycloak-test/realms/moh_applications/clients/edrd/main.tf
Updating roles for EDRD clients. Promoting EDRD-PORTAL to Production.
EDRD client onboarding.
=> promote edrd-portal to prod

keycloak-test/realms/moh_applications/clients/sa-dbaac-portal/main.tf, keycloak-test/realms/moh_applications/clients/sa-hibc-service-bc-portal/main.tf, keycloak-test/realms/moh_applications/clients/sa-sfdc/main.tf
adding two urls to sa-dbaac-portal, sa-hibc-service-bc-portal. adding one url to sa-sfdc
Requested by client for SAT environment in test.
=> adding uri redirects to 3 sa clients in test

keycloak-dev/realms/moh_applications/clients/phlat-service/main.tf, keycloak-prod/realms/moh_applications/clients/phlat-web/main.tf, keycloak-test/realms/moh_applications/clients/phlat-service/main.tf
Adding a cloudfront domain to redirect uri in prod for PHLAT-WEB.
Requested by client.
=> add url redirect to phlat-web in prod

keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding PRP_LTC, PRP_ReportProgram_LTC and PRP_ReportSection_LTC roles to HSPP in test env.
=> adding 3 roles to hspp test

keycloak-test/realms/moh_applications/clients/primary-care/main.tf
adding https://healthbc--hlthbcemr.sandbox.my.salesforce.com/*
https://healthbc--hlthbcemr.sandbox.my.site.com/*
https://healthbc--previewqa.sandbox.my.salesforce.com/*
https://healthbc--previewqa.sandbox.my.site.com/* to uri redirects for primary-care in test env.
Requested by client
=> adding 4 uri redirects to primary care test

keycloak-dev/realms/moh_applications/clients.tf, keycloak-dev/realms/moh_applications/clients/pho-rsc/main.tf, keycloak-dev/realms/moh_applications/clients/pho-rsc/variables.tf
Implement IDP restriction module for POSIT/PHO-RSC. Deprecating IDIR from that dev client.
=> apply-idp-restriction-posit-dev

keycloak-dev/realms/moh_applications/clients.tf, keycloak-dev/realms/moh_applications/clients/ien/main.tf, keycloak-dev/realms/moh_applications/clients/ien/variables.tf
Removing login with IDIR option of IEN by applying IDP restriction module.
=> apply idp restriction module to DEV IEN

keycloak-prod/realms/moh_applications/clients/phlat-service/main.tf
Changing PHLAT-service claim value in prod to 00026841
Requested by Gary
=> changing claim value

keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Whitelisting new PRIMARY-CARE urls.
Client request.
=> add primary-care urls to test

keycloak-prod/realms/moh_applications/groups/registries-connections-team/main.tf
Add bulk-removal role to registries team on Prod.
=> allow bulk-remove for prod  registries group

keycloak-test/realms/moh_applications/clients/edrd-portal/main.tf, keycloak-test/realms/moh_applications/clients/edrd/main.tf, keycloak-test/realms/moh_applications/clients/sa-sfdc/main.tf
Whitelisting new sandbox URLs. Client request.
=> add redirect urls

keycloak-dev/realms/moh_applications/clients/pidp-webapp/main.tf
Removing bceid from allowed idps for PIDP. Adding bcprovider.
=> fix idp restriction module for pidp

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding new role HSPP_Restricted_CDR to prod and test for HSPP client.
=> adding new role to hspp client in test and prod

keycloak-prod/realms/moh_applications/clientScopes.tf
Adding scopes that represent IDPs to Prod environment. 
IDP restriction module deployment to Prod environmnet.
=> add keycloak prod idp scopes

keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Adding PC_NavigatorLead and HealthlinkBC_PharmacistLead roles to primary care application in test.
=> adding two new roles to primary care application in test env

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding new role HSPP_Restricted_CHSP to HSPP client in test and prod environments.
Change requested by client.
=> adding new role to hspp client in test and prod env

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/florizel-training/main.tf, keycloak-test/realms/moh_applications/clients/florizel/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding new role HSPP_Restricted_MEDISLTC to test and prod for HSPP client. And adding manual changes as per Filip.
Role requested by client. Manual changes as per Filip.
=> Hspp new role test prod

keycloak-prod/realms/moh_applications/clients/florizel/main.tf, keycloak-test/realms/moh_applications/clients/florizel-training/main.tf, keycloak-test/realms/moh_applications/clients/florizel/main.tf
Importing manual changes made during meeting with Client. Production roles will be updated at a later date.
Florizel client onboarding
=> update florizel roles

keycloak-prod/realms/moh_applications/clients/florizel/main.tf, keycloak-test/realms/moh_applications/clients/florizel-training/main.tf, keycloak-test/realms/moh_applications/clients/florizel/main.tf
Sync all Florizel environments.
Florizel client onboarding
=> update florizel configuration

keycloak-prod/realms/moh_applications/groups.tf, keycloak-prod/realms/moh_applications/groups/florizel-management/main.tf, keycloak-prod/realms/moh_applications/groups/florizel-management/output.tf, keycloak-prod/realms/moh_applications/groups/florizel-management/variables.tf, keycloak-prod/realms/moh_applications/groups/florizel-management/versions.tf, keycloak-test/realms/moh_applications/groups.tf, keycloak-test/realms/moh_applications/groups/florizel-management/main.tf, keycloak-test/realms/moh_applications/groups/florizel-management/output.tf, keycloak-test/realms/moh_applications/groups/florizel-management/variables.tf, keycloak-test/realms/moh_applications/groups/florizel-management/versions.tf
Creating florizel admin groups.
=> add florizel admin group

keycloak-prod/main.tf, keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/emaccs-ums/main.tf, keycloak-prod/realms/moh_applications/clients/emaccs-ums/outputs.tf, keycloak-prod/realms/moh_applications/clients/emaccs-ums/variables.tf, keycloak-prod/realms/moh_applications/clients/emaccs-ums/versions.tf, keycloak-prod/realms/moh_citizen/clients.tf, keycloak-prod/realms/moh_citizen/clients/emaccs/main.tf, keycloak-prod/realms/moh_citizen/clients/emaccs/outputs.tf, keycloak-prod/realms/moh_citizen/clients/emaccs/versions.tf, keycloak-prod/realms/moh_citizen/versions.tf
Copy the EMACCs client from test to production.
EMACCS client onboarding
- [N/A] [CMDB](https://cmdb.hlth.gov.bc.ca/cmdbuildProd/ui/#classes/Application/cards) is updated, if applicable.
=> promote EMACCS to Prod

keycloak-prod/realms/moh_applications/clients/pidp-service/main.tf
=> add prp permissions

keycloak-test/realms/moh_applications/clients/edrd/main.tf
Adding URL to test env for EDRD client.
=> adding url to test env for edrd client

keycloak-test/realms/moh_applications/clients/florizel/main.tf
Changing login theme to default so that Florizel devs can troubleshoot it in test environment.
=> update florizel config for troubleshooting

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding new role HSPP_Restricted_CIHI to prod and test envs.
Change requested by client.
=> adding new role to hspp in test and prod env

keycloak-dev/realms/moh_applications/clients/licence-status/main.tf, keycloak-test/realms/moh_applications/clients/licence-status/main.tf, keycloak-test/realms/moh_applications/clients/prp-web/main.tf
Adding PHARM role to license-status in dev and test. adding scope mapping to prp-web in test env.
Change requested by client.
=> adding license-status pharm role and scope mapping prp

keycloak-prod/realms/moh_applications/clients/prp-web/main.tf
PROD: Add LICENCE-STATUS: PHARM scope mapping to PRP-WEB client.
Requested by PRP-WEB project developer.
=> PROD: Add LICENCE-STATUS: PHARM scope mapping to PRP-WEB client.

keycloak-prod/realms/moh_applications/clients/panorama/main.tf
Changing https://pan-reports-prd.bchealthcloud.ca to https://pan-reports.bchealthcloud.ca in Panorama Prod env.
Change (correction) requested by Fiona.
=> change panorama prod url

keycloak-test/realms/moh_applications/clients/tpl/main.tf
TEST: Add redirects for TPL staging and new QA env.
Requested by project team to advance UAT. Urgent.
=> TEST: Add redirects for TPL staging and new QA env.

keycloak-test/realms/moh_applications/clients.tf, keycloak-test/realms/moh_applications/clients/ivf-portal/main.tf, keycloak-test/realms/moh_applications/clients/ivf-portal/outputs.tf, keycloak-test/realms/moh_applications/clients/ivf-portal/variables.tf, keycloak-test/realms/moh_applications/clients/ivf-portal/versions.tf, keycloak-test/realms/moh_applications/clients/user-management-service/main.tf, keycloak-test/realms/moh_applications/clients/user-management/main.tf
Creating IVF-PORTAL client with IDP restriction module on Test environment. 
New client onboarding. This is a Salesforce app - configuration is similar to other Salesforce integrations, like PRIMARY-CARE.
=> Create ivf test client

keycloak-test/realms/moh_applications/clients.tf, keycloak-test/realms/moh_applications/clients/florizel-training/main.tf, keycloak-test/realms/moh_applications/clients/florizel-training/variables.tf, keycloak-test/realms/moh_applications/clients/genesys-training/main.tf, keycloak-test/realms/moh_applications/clients/genesys-training/variables.tf
Introduce idp restriction module in florizel and genesys training.
Idp restriction module work.
=> Idp restriction module florizel genesys training

keycloak-test/realms/moh_applications/clients/edrd-portal/main.tf, keycloak-test/realms/moh_applications/clients/edrd/main.tf, keycloak-test/realms/moh_applications/clients/icy/main.tf, keycloak-test/realms/moh_applications/clients/ivf-portal/main.tf, keycloak-test/realms/moh_applications/clients/sa-dbaac-portal/main.tf, keycloak-test/realms/moh_applications/clients/sa-hibc-service-bc-portal/main.tf, keycloak-test/realms/moh_applications/clients/sa-sfdc/main.tf
Add missing scopes to Salesforce clients on TEST environment.
IVF client onboarding - troubleshooting meeting.
=> Update ivf and other salesforce test config

keycloak-test/realms/moh_applications/groups.tf, keycloak-test/realms/moh_applications/groups/ivf-portal-management/main.tf, keycloak-test/realms/moh_applications/groups/ivf-portal-management/output.tf, keycloak-test/realms/moh_applications/groups/ivf-portal-management/variables.tf, keycloak-test/realms/moh_applications/groups/ivf-portal-management/versions.tf
Setting up IVF-PORTAL admin group
=> configure ivf-portal admin group

keycloak-test/realms/moh_applications/clients/hcim_fha_test/main.tf
Removing dash from hcim_org protocol mapper. FHA-Testing -> FHATesting
=> removing dash

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
Add new roles to HSPP Test and Prod
=> new hspp roles

keycloak-test/realms/moh_applications/clients/edrd-portal/main.tf, keycloak-test/realms/moh_applications/clients/edrd/main.tf, keycloak-test/realms/moh_applications/clients/sa-dbaac-portal/main.tf, keycloak-test/realms/moh_applications/clients/sa-hibc-service-bc-portal/main.tf, keycloak-test/realms/moh_applications/clients/sa-sfdc/main.tf
Updating Salesforce redirect URLs.
=> salesforce redirect urls

keycloak-test/realms/moh_applications/clients.tf, keycloak-test/realms/moh_applications/clients/ivf-portal/main.tf, keycloak-test/realms/moh_applications/clients/ivf-portal/variables.tf
Adding attribute mappers to IVF-PORTAL client on Test
=> add mapers to ivf

keycloak-dev/realms/moh_applications/clients/connect/main.tf, keycloak-dev/realms/moh_applications/clients/forms/main.tf, keycloak-dev/realms/moh_applications/clients/hcimweb/main.tf, keycloak-dev/realms/moh_applications/clients/hdpbc/main.tf, keycloak-dev/realms/moh_applications/clients/ien/main.tf, keycloak-dev/realms/moh_applications/clients/maid/main.tf, keycloak-dev/realms/moh_applications/clients/metaspace/main.tf, keycloak-dev/realms/moh_applications/clients/mspdirect-web/main.tf, keycloak-dev/realms/moh_applications/clients/pho-rsc/main.tf, keycloak-dev/realms/moh_applications/clients/pidp-webapp/main.tf, keycloak-dev/realms/moh_applications/clients/plr/main.tf, keycloak-dev/realms/moh_applications/clients/user-management/main.tf, keycloak-prod/realms/moh_applications/clients/hamis/main.tf
Updating HAMIS, HCIMWEB and default scopes.
Mailbox requests and Keycloak version upgrade.
=> Update hamis hcimweb

keycloak-test/realms/moh_applications/clients/sa-sfdc/main.tf
New roles for the SAT application.
=> add new sat roles

keycloak-dev/realms/moh_applications/clients.tf, keycloak-dev/realms/moh_applications/clients/hcap-fe/main.tf, keycloak-dev/realms/moh_applications/clients/hcap-fe/outputs.tf, keycloak-dev/realms/moh_applications/clients/hcap-fe/versions.tf, keycloak-dev/realms/moh_applications/clients/hcap-service/main.tf, keycloak-dev/realms/moh_applications/clients/hcap-service/outputs.tf, keycloak-dev/realms/moh_applications/clients/hcap-service/variables.tf, keycloak-dev/realms/moh_applications/clients/hcap-service/versions.tf, keycloak-dev/realms/moh_applications/clients/user-management-service/main.tf
DEV: HCAP clients transferred from TEST.
Requested by HCAP development team.
=> DEV: HCAP clients transferred from TEST.

keycloak-dev/realms/moh_applications/clients/user-management-service/main.tf, keycloak-dev/realms/moh_applications/groups.tf, keycloak-dev/realms/moh_applications/groups/prime-management/main.tf, keycloak-dev/realms/moh_applications/groups/prime-management/output.tf, keycloak-dev/realms/moh_applications/groups/prime-management/variables.tf, keycloak-dev/realms/moh_applications/groups/prime-management/versions.tf
DEV: PRIME management group for UMC access.
Requested by development team.
=> DEV: PRIME management group for UMC access.

keycloak-dev/realms/moh_applications/clients/user-management/main.tf
DEV: PRIME management group scope mappings for UMC.
Requested by DEV team.
=> DEV: PRIME management group scope mappings for UMC.

keycloak-test/realms/moh_applications/clients/alr/main.tf
=> update alr config

keycloak-prod/realms/moh_applications/clients.tf, keycloak-prod/realms/moh_applications/clients/panorama/main.tf, keycloak-prod/realms/moh_applications/clients/panorama/variables.tf
PROD: Panorama use IDP restriction module.
Client requested.
=> PROD: Panorama use IDP restriction module.

keycloak-dev/realms/moh_applications/clientScopes.tf
Add BCSC scopes for PRIME and HCAP.
Requested by development teams.
=> Add BCSC scopes for PRIME and HCAP.

keycloak-dev/realms/moh_applications/clients/mspdirect-web/main.tf, keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Update primary-care on Test so that they use refresh tokens. Persist manual mspdirect config changes.
=> use refresh tokens primary care

keycloak-test/realms/moh_applications/clients/ivf-clinic-portal/main.tf
Add scope mapper so license status shows up in token claim.
=> Update ivf clinic config

keycloak-test/realms/moh_applications/clients/tpl/main.tf
Whitelisting UL for TPL client.
=> add tpl redirect url

keycloak-prod/realms/moh_applications/clients/pnet-api-client-generation/main.tf, keycloak-test/realms/moh_applications/clients/pnet-api-client-generation/main.tf, keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Add role to Primary Care client
=> add primary-care role

keycloak-prod/realms/moh_applications/clients/hspp/main.tf, keycloak-test/realms/moh_applications/clients/hspp/main.tf
=> hspp roles
