- keycloak-dev/realms/moh_applications/user-management-service/main.tf
- keycloak-dev/realms/moh_applications/user-management/main.tf
- keycloak-prod/realms/moh_applications/user-management-service/main.tf
- keycloak-prod/realms/moh_applications/user-management/main.tf
- keycloak-test/realms/moh_applications/user-management-service/main.tf
- keycloak-test/realms/moh_applications/user-management/main.tf
two new roles: 
- manage-own-groups
- manage-all-groups
USER_MANAGEMENT mapper: groups are now shown in access token
manage-user-groups will be deprecated - I will delete it after code review
> add group management roles

- keycloak-dev/realms/moh_applications/sat-eforms/main.tf
- keycloak-test/realms/moh_applications/sat-eforms/main.tf
Requested by James Hollinger of the PIDP team.
The PIPD team requested this new role because they want to "enrol" users in it. The PIDP client already has the required scope client role mapping for "view-client-sat-eforms", so it doesn't need to be updated with a new role.
> Add new role to SAT-EFORMS client in DEV and TEST.

- keycloak-dev/realms/moh_applications/connect/main.tf
- keycloak-prod/realms/moh_applications/connect/main.tf
- keycloak-test/realms/moh_applications/connect/main.tf
Update so the CONNECT team doesn't have warning about refresh token.
> update refresh tokens attr for connect dev

- keycloak-dev/realms/moh_applications/dmft-service/main.tf
- keycloak-dev/realms/moh_applications/pidp-service/main.tf
- keycloak-dev/realms/moh_applications/user-management-service/main.tf
Give the PIDP-SERVICE service account permission to manage DMFT-SERVI…CE roles. Also rename the DMFT-SERVICE-ACCOUNT client to simply DMFT-SERVICE to be consistent with other clients.
> PIDP-SERVICE service account to manage DMFT-SERVICE roles

- keycloak-dev/realms/moh_applications/user-management-service/main.tf
- keycloak-dev/realms/moh_applications/user-management/main.tf
SAT-DRUG-MANAGEMENT-1 and SAT-CASE-MANAGEMENT-1 deleted from DEV manually
manually deleted scope mappings and removed them from tf.state file, not to trigger the scope-mapping deletion bug.
Manually removed two corresponding UMS roles from tf.state file
> remove sat-case sat-drug roles and scope mappings

- keycloak-test/realms/moh_applications/hcap-service/main.tf
- keycloak-test/realms/moh_applications/hcap-service/outputs.tf
- keycloak-test/realms/moh_applications/hcap-service/variables.tf
- keycloak-test/realms/moh_applications/hcap-service/versions.tf
- keycloak-test/realms/moh_applications/main.tf
Add HCAP service account to manage HCAP roles via UMS. Will add stub HCAP client in another PR.
> Add HCAP service account to manage HCAP roles via UMS

- keycloak-test/realms/moh_applications/hsiar/main.tf
Our login template requires a name or else an internal Keycloak exception is produced when you attempt to login.
> Add a 'name' to the HSIAR client. 

- keycloak-dev/realms/moh_applications/pidp-service/main.tf
- keycloak-dev/realms/moh_applications/pidp-webapp/main.tf
- keycloak-test/realms/moh_applications/pidp-service/main.tf
- keycloak-test/realms/moh_applications/pidp-webapp/main.tf
Remove remove the feature_amh_demo role from PIDP-SERVICE at the request of James Hollinger.
After this PR, I will submit one for PROD.
> Remove remove the feature_amh_demo role 

- keycloak-prod/realms/moh_applications/pidp-service/main.tf
- keycloak-prod/realms/moh_applications/pidp-webapp/main.tf
need to re-run the apply command to recreate deleted scope mappings
> remove pidp role from prod

- keycloak-test/realms/moh_applications/hsiar/main.tf
- keycloak-test/realms/moh_applications/prime-application-local/main.tf
Before running apply, 4 mappers need to be deleted, because they were created manually and adding them would create conflict
> add prime and hsiar mappers

- keycloak-test/realms/moh_applications/main.tf
- keycloak-test/realms/moh_applications/prime-application-local/main.tf
- keycloak-test/realms/moh_applications/prime-application-service-account/main.tf
- keycloak-test/realms/moh_applications/prime-application-service-account/variables.tf
- keycloak-test/realms/moh_applications/prime-application-test/main.tf
- keycloak-test/realms/moh_applications/prime-careconnect-access/main.tf
- keycloak-test/realms/moh_applications/prime-careconnect-access/variables.tf
- keycloak-test/realms/moh_applications/prime-medinet-access/main.tf
- keycloak-test/realms/moh_applications/prime-medinet-access/variables.tf
- keycloak-test/realms/moh_applications/user-management-service/main.tf
- keycloak-test/realms/moh_applications/user-management/main.tf
Enable prime-application-test in UMC.
Import prime-application-service-account changes.
Import careconnect and medinet scope mappings and service account roles.
> allow prime-test in umc and import service account test roles

- keycloak-test/realms/moh_applications/bcer-cp/main.tf
Updating Valid Redirect URIs for the BCER Data Portal client in Keycloak Test.
Setting up new AWS accounts for BCER.
 
> Update Valid Redirect URIs for BCER Data Portal in Test

- keycloak-test/realms/moh_applications/main.tf
- keycloak-test/realms/moh_applications/primary-care/main.tf
- keycloak-test/realms/moh_applications/primary-care/variables.tf
* Add mappers for new user attributes.
* Add scope for LICENCE-STATUS.
* Remove unused scopes.
PRIMARY-CARE needs new attributes. These attributes will eventually be added to users during PIDP enrolment.
PRIMARY-CARE also needs access to user's the LICENCE-STATUS.
I have removed some unneeded scopes in accordance with our new understanding of scopes.
 
[^2]: Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of …
> Primary care new attributes

- keycloak-dev/realms/moh_applications/pho-rsc/main.tf
Adding two `role `resources to PHO-RSC dev. 
Roles were created manually and imported - that's why terraform plan won't show any changes. The two `roles` will actually be used as groups on the PHO-RSC side, but we don't leverage `groups` resource for individual clients. PHO-RSC is fine with passing them in token with other roles.
 
> add pho-rsc roles

- keycloak-test/realms/moh_applications/hsiar/main.tf
Add roles for HSIAR client on TEST env.
AM Team Mailbox request.
 
> add hsiar roles

- keycloak-dev/realms/moh_applications/pho-rsc/main.tf
- keycloak-prod/realms/moh_applications/pho-rsc/main.tf
- keycloak-prod/realms/moh_applications/user-management-service/main.tf
- keycloak-prod/realms/moh_applications/user-management/main.tf
Update PHO-RSC client on Prod environment, so it matches configuration from Dev. 
Restricting Web Origins only to redirect URIs.
Adding role to UMS/UMC so PHO-RSC roles can be assigned via UMC.
PHO-RSC moving to prod.
 
> Update pho rsc prod client

- keycloak-prod/realms/moh_applications/prime-application/main.tf
- keycloak-test/realms/moh_applications/prime-application-local/main.tf
- keycloak-test/realms/moh_applications/prime-application-test/main.tf
Adding new role to PRIME clients
'external_gpid_access’ role will allow PRIME team to control access to API endpoint
 
> Add role external_gpid_access for prime

- keycloak-test/realms/moh_applications/prime-application-local/main.tf
- keycloak-test/realms/moh_applications/prime-application-test/main.tf
Change `Allowed CORS Origins` to * on test clients.
PRIME has CORS issues for tests clients because `+` doesn't include `*` from Valid redirect URIs.
 
> fix cors issue for prime

- keycloak-prod/realms/moh_applications/prime-medinet-access/main.tf
- keycloak-test/realms/moh_applications/prime-medinet-access/main.tf
Add scope mapping for external_gpid_access
Add scope mapping for external_gpid_access
 
> Add scope mapping for external_gpid_access

- README.md
- keycloak-dev/realms/moh_applications/user-management/main.tf
- main.tf
Changing the s3 bucket backend configuration.
Update README.md
Update the URL to test things out
AWS `sandbox` account/environment will be replaced by `tools`. Terraform state file was already transferred to `tools`. 
Updating the s3 backend config so it points to the `tools` environment.
Note: terraform plan for this PR will not work until the `AWS_S3_BACKEND_ROLE_ARN` secret is updated in the repo.
 
[^2]: Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not interfere with existing configuration, they can be ignored. Here is an example of one:
> switch remote state update readme and add test change

- keycloak-test/realms/moh_applications/primary-care/main.tf
Change the endorser_data mapper from type String (default) to JSON.
The endorser_data will be a list, e.g. 
> Multi-valued:
> `"endorser_data": ["CPN.00063660.BC.PRS","CPN.00099999.BC.PRS"]`
> 
> Single-valued:
> `"endorser_data": ["CPN.00063660.BC.PRS"]`
If you use the default String type, it will be encoded as an escaped-string, not JSON, e.g. `"endorser_data": "[\"CPN.00063660.BC.PRS\"]"`.
NA
[^2]: Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` …
> PRIMARY-CARE endorser_data should be JSON

- keycloak-test/realms/moh_applications/primary-care/main.tf
Adding new BC Provider mappers to PRIMARY-CARE client on test
 
> add-primarycare-mappers

- keycloak-test/realms/moh_applications/hsiar/main.tf
New role for HSIAR on test env
 
[^2]: Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not interfere with the existing configuration, they can be ignored. Here is an example of one:
> new role for hsiar on test env

- keycloak-test/realms/moh_applications/primary-care/main.tf
Add existing attributes to access token. Remove unused attributes.
PRIMARY-CARE has requested attributes be added to the ID token, not just the access token. 
Some of the attributes that were recently added, e.g. `isMd`, will not be needed directly, but will be mapped into a client role for the LICENCE-STATUS client. Mappers have been removed. IDP mappers will be added to map `isMd` into a client role.
 
[^2]: Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform …
> PRIMARY-CARE: Add attributes to ID token. Remove unused attributes.

- keycloak-test/realms/moh_applications/hsiar/main.tf
- keycloak-test/realms/moh_applications/tpl/main.tf
Added new role for HSIAR test env (ITSB_DIGI), rearranged the order to alphabetical. Added new redirect URI for TPL. 
 
[^2]: Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not interfere with the existing configuration, they can be ignored. Here is an example of one:
> add role for hsiar and redirect url for tpl

- keycloak-prod/realms/moh_applications/realm-roles/cgi-application-support/main.tf
- keycloak-prod/realms/moh_applications/realm-roles/cgi-application-support/output.tf
- keycloak-prod/realms/moh_applications/realm-roles/cgi-application-support/variables.tf
- keycloak-prod/realms/moh_applications/realm-roles/cgi-application-support/versions.tf
- keycloak-prod/realms/moh_applications/realm-roles/manage-realm/main.tf
- keycloak-prod/realms/moh_applications/realm-roles/manage-realm/output.tf
- keycloak-prod/realms/moh_applications/realm-roles/manage-realm/variables.tf
- keycloak-prod/realms/moh_applications/realm-roles/manage-realm/versions.tf
- keycloak-prod/realms/moh_applications/realm-roles/manage-users/main.tf
- keycloak-prod/realms/moh_applications/realm-roles/manage-users/output.tf
- keycloak-prod/realms/moh_applications/realm-roles/manage-users/variables.tf
- keycloak-prod/realms/moh_applications/realm-roles/manage-users/versions.tf
- keycloak-prod/realms/moh_applications/realm-roles/view-users/main.tf
- keycloak-prod/realms/moh_applications/realm-roles/view-users/output.tf
- keycloak-prod/realms/moh_applications/realm-roles/view-users/variables.tf
- keycloak-prod/realms/moh_applications/realm-roles/view-users/versions.tf
- keycloak-prod/realms/moh_applications/realmRoles.tf
Add realm roles to the prod environment. Realm roles were imported.
 
> manage realm roles on prod env

- keycloak-prod/realms/moh_applications/clients/pidp-service/main.tf
Allow PIDP-SERVICE to manage LICENCE-STATUS in PROD.
The PIPD application needs to be able to manage LICENCE-STATUS for DMFT. They already went to PROD, and this is causing failures in production.
 
> PIDP-SERVICE: Allow to manage LICENCE-STATUS in PROD.

- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/primary-care/main.tf
- keycloak-prod/realms/moh_applications/clients/primary-care/outputs.tf
- keycloak-prod/realms/moh_applications/clients/primary-care/variables.tf
- keycloak-prod/realms/moh_applications/clients/primary-care/versions.tf
Promote the PRIMARY-CARE client to PROD.
We have been requested to set-up some PRIMARY-CARE users in PROD. This isn't really in the right sequence, as PRIMARY-CARE has not been deployed to PROD yet, so any users we won't set-up aren't usable or testable. In any case, we need a client with roles if we're to assign them to users, so we're promoting the client to PROD now. It's not a security risk, but it will likely require changes as they are still requesting configuration changes in TEST.
 
[^2]: Keep in mind that …
> PRIMARY-CARE: Create client in PROD.

- keycloak-prod/realms/moh_applications/clients/primary-care/main.tf
This is just a placeholder URL. Not the real one.
> PRIMARY-CARE: Add redirect URL. Requires at least one. 

- keycloak-prod/realms/moh_applications/clients/user-management-service/main.tf
Add Primary Care role.
This role can be assigned to access management groups to allow them to manage Primary Care users using the User Management Console.
 
> USER-MANAGEMENT-SERVICE PROD: Add Primary Care available role.

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/prime-vihacerner-access/main.tf
- keycloak-test/realms/moh_applications/clients/prime-vihacerner-access/outputs.tf
- keycloak-test/realms/moh_applications/clients/prime-vihacerner-access/variables.tf
- keycloak-test/realms/moh_applications/clients/prime-vihacerner-access/versions.tf
Creating PRIME-VIHACERNER-ACCESS service account in the test environment.
A new system account for Island Health was requested. The account should be similar to PRIME-CARECONNECT-ACCESS, but named PRIME-VIHACERNER-ACCESS?
> PRIME-VIHACERNER-ACCESS: create service account in test

- keycloak-prod/realms/moh_applications/clients/primary-care/main.tf
- keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Add/ remove roles from PRIMARY-CARE client on test and prod environments. 
PRIMARY-CARE updated a list of Salesforce Personas, changes need to be reflected in Keycloak.
 
[^2]: Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not interfere with the existing configuration, they can be ignored. Here is an example of one:
> update primary-care roles

- keycloak-prod/realms/moh_applications/realm-roles/manage-users/main.tf
Add view-client-primary-care role to ManageUsers in Prod env.
This role is needed to manage PRIMARY-CARE client in UMC.
 
> add view-client-primary-care role to ManageUsers in Prod

- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/hsppcliip/main.tf
- keycloak-prod/realms/moh_applications/clients/hsppcliip/outputs.tf
- keycloak-prod/realms/moh_applications/clients/hsppcliip/versions.tf
Adding configuration for HSPPCLIIP to prod environment including:
Specified Redirect URL:
- https://hsppcliip.healthideas.gov.bc.ca/*
Requested roles:
- HSPP_ALL
- HSPP_OKR
- HSPP_HumanResource
- HI_Administrator
> HSPPCLIIP - Add client configuration to prod

- keycloak-prod/realms/moh_applications/clients/primary-care/main.tf
Adding URL to PRIMARY-CARE client on prod env.
 
> add redirect url for primary-care on prod

- .github/pull_request_template.md
- keycloak-prod/realms/moh_applications/clients/primary-care/main.tf
- keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Adding IDP mappers for PRIMARY-CARE in test and prod.
IDP value needs to be accessible through token sent from Keycloak.
 
> add IDP mapper for PRIMARY-CARE and update PR template

- keycloak-prod/realms/moh_applications/clients/fmdb/main.tf
Adding AWS Redirect URI.
FMDB Prod will eventually cutover to AWS and the vanity url (fmdb.hlth.gov.bc.ca) won't be in use for go-live.
 
> Adding FMDB Prod Redirect URI for AWS migration

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/hcim_lra/main.tf
- keycloak-test/realms/moh_applications/clients/hcim_lra/outputs.tf
- keycloak-test/realms/moh_applications/clients/hcim_lra/versions.tf
Adding HCIM_LRA client to Test environment.
Request from Kim Glidden. Modelled after HCIM_VIHA.
 
> Added HCIM_LRA client.

- keycloak-prod/realms/moh_applications/groups.tf
- keycloak-prod/realms/moh_applications/groups/primary-care-access-team/main.tf
- keycloak-prod/realms/moh_applications/groups/primary-care-access-team/output.tf
- keycloak-prod/realms/moh_applications/groups/primary-care-access-team/variables.tf
- keycloak-prod/realms/moh_applications/groups/primary-care-access-team/versions.tf
Updated PRIMARY-CARE group on test and created one on prod environment.
The changes will allow PRIMARY-CARE team to assign application roles through UMC.
 
> create primary-care-access group on prod

- keycloak-test/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-test/realms/moh_applications/clients/user-management/main.tf
Create role view-client-hspp and add a scope mapping. 
HSPP want to utilize UMC tool for user management.
 
> enable hspp management in umc

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/plr-prp/main.tf
- keycloak-test/realms/moh_applications/clients/plr-prp/variables.tf
Added PLR_REV/CONSUMER scope mappings/role to PLR-PRP allow access to PLR Review environment.
The PRP application needs to query the PLR review environment via the PLR-PRP service account.
 
> Added PLR_REV/CONSUMER role to allow access to PLR Review environment.

- keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Adding redirect URLs for PRIMARY-CARE client on test
AM Team mailbox request.
 
> add redirect urls form primary-care on test

- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding the following roles to HSPP Test
- HSPP_ReportProgram_Invictus
- HSPP_ReportSection_Invictus
- HSPP_Report_Invictus
Adding new roles to HSPP Test as per Joyce's request so that they can test and signoff before the changes are promoted to Prod.
 
> Adding new roles to HSPP Test as per Joyce's request

- keycloak-prod/realms/moh_applications/groups.tf
- keycloak-prod/realms/moh_applications/groups/hspp-management/main.tf
- keycloak-prod/realms/moh_applications/groups/hspp-management/output.tf
- keycloak-prod/realms/moh_applications/groups/hspp-management/variables.tf
- keycloak-prod/realms/moh_applications/groups/hspp-management/versions.tf
Create HSPP management group in Prod env.
This will allow HSPP admins to manage user roles through UMC.
 
> create hspp group on prod env

- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding HTTPS localhost to HSPP Test client to match HSIAR Test functionality.
Adding new Valid Redirect URI to HSPP Test as per Gary's request.
 
> Adding HTTPS localhost valid redirect uri to HSPP Test as per Gary Sun

- keycloak-prod/realms/moh_applications/clients/hspp/main.tf
Adding the following roles to HSPP Prod
- HSPP_ReportProgram_Invictus
- HSPP_ReportSection_Invictus
- HSPP_Report_Invictus
Adding new roles to HSPP Prod as per Joyce's request.
 
> Adding new roles to HSPP Prod as per Joyce's request

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/plr-lra/main.tf
- keycloak-test/realms/moh_applications/clients/plr-lra/outputs.tf
- keycloak-test/realms/moh_applications/clients/plr-lra/variables.tf
- keycloak-test/realms/moh_applications/clients/plr-lra/versions.tf
- keycloak-test/realms/moh_applications/clients/plr-qa-consumer/main.tf
- keycloak-test/realms/moh_applications/clients/plr-qa-dsr-user/main.tf
- keycloak-test/realms/moh_applications/clients/plr-qa-primary-source/main.tf
- keycloak-test/realms/moh_applications/clients/plr-qa-regadmin/main.tf
- keycloak-test/realms/moh_applications/clients/plr-qa-secondary-source/main.tf
Create PLR-LRA client to provide access to PLR APIs for LRA. Fix a description field typo in the other PLR API clients.
Kim Glidden is requesting this client for LRA to access PLR APIs on behalf of LRA.
 
> Create PLR-LRA client to provide access to PLR APIs for LRA

- keycloak-test/realms/moh_applications/clients/plr-lra/main.tf
- keycloak-test/realms/moh_applications/clients/plr-qa-consumer/main.tf
- keycloak-test/realms/moh_applications/clients/plr-qa-dsr-user/main.tf
- keycloak-test/realms/moh_applications/clients/plr-qa-moh-approver/main.tf
- keycloak-test/realms/moh_applications/clients/plr-qa-primary-source/main.tf
- keycloak-test/realms/moh_applications/clients/plr-qa-regadmin/main.tf
- keycloak-test/realms/moh_applications/clients/plr-qa-secondary-source/main.tf
Removing unneeded protocol mappers. Created by Keycloak by default for service accounts. Not needed. Caused the Terraform apply to fail because the mappers already exist by default when service accounts are enabled.
PLR-API access for LRA requested by Kim Glidden.
 
Same as last PR.
> Removed unneeded mappers.

- keycloak-test/realms/moh_applications/groups.tf
- keycloak-test/realms/moh_applications/groups/hspp-management/main.tf
- keycloak-test/realms/moh_applications/groups/hspp-management/output.tf
- keycloak-test/realms/moh_applications/groups/hspp-management/variables.tf
- keycloak-test/realms/moh_applications/groups/hspp-management/versions.tf
Create HSPP Management group on test environment.
Mailbox request. This will allow HSPP admins to manage user and group permissions. 
 
> create hspp management group on test env

- keycloak-prod/realms/moh_applications/clients/hspp/main.tf
- keycloak-test/realms/moh_applications/clients/bcer-cp/main.tf
- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding HSPP roles to Test and Prod. Adding redirect URL to BCER-CP on Test
HSPP - team mailbox request. BCER-CP url  was previously added through admin console.
> create hspp roles on test and prod and add url for bcer-cp

- keycloak-dev/realms/moh_applications/clients/dmft-webapp/main.tf
- keycloak-dev/realms/moh_applications/clients/prime-webapp-enrollment/main.tf
- keycloak-test/realms/moh_applications/clients/dmft-webapp/main.tf
- keycloak-test/realms/moh_applications/clients/prime-application-dev/main.tf
- keycloak-test/realms/moh_applications/clients/prime-application-local/main.tf
- keycloak-test/realms/moh_applications/clients/prime-application-test/main.tf
- keycloak-test/realms/moh_applications/clients/prime-webapp-enrollment/main.tf
Adding birthday attribute mappers to DMFT and PRIME applications on the test environment.
DMFT and PRIME are using the `birthdate` attribute, passed from BCSC. Currently, it's being passed to the token because of the `profile` scope. Those changes will allow removing the `birthdate` attribute from the scope so that other applications don't have access to it.
 
> add birthdate mapper to dmft and prime

- keycloak-test/realms/moh_applications/clients/plr-lra/main.tf
Update PLR-LRA Test orgId to 00025902 as per Kim Glidden.
David had created the PLR-LRA Test client prior to the Org existing, so an update is necessary.
 
> Update PLR-LRA Test orgId as per Kim

- keycloak-prod/realms/moh_applications/clients/hspp/main.tf
- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding `HSPP_ReportProgram_OKR `and `HSPP_ReportSection_OKR` roles to test and prod env for HSPP client, as per mailbox request.
 
> add hspp roles for test and prod

- keycloak-prod/realms/moh_applications/clients/primary-care/main.tf
Adding valid redirect URIs as requested by Primary Care team through Renaldo
These are required as the training environment uses PROD users
 
> Adding valid redirect URIs as

- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding hspp redirect URL on test environment.
 
> add redirect url to hspp test

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/forms/main.tf
- keycloak-test/realms/moh_applications/clients/forms/outputs.tf
- keycloak-test/realms/moh_applications/clients/forms/versions.tf
Adding new FORMS Dev/Test client for Keycloak Test.
FORMS is a Drupal application looking to be onboarded in an expedited manner. See [AB#10435 - Add Dev/Test FORMS client configuration to Keycloak Test](https://dev.azure.com/cgi-vic-hlth/AM%20Team/_workitems/edit/10435) for more details.
 
[^2]: Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not …
> Onboarding new FORMS client in Test

- keycloak-prod/realms/moh_applications/groups/hspp-management/main.tf
- keycloak-test/realms/moh_applications/groups/hspp-management/main.tf
Assigning `create-user` and `manage-user-details` role to `HSPP Management` group on test and prod.
Mailbox request. HSPP business client would like to have pre-approved users to be added before they access keycloak. 
 
> add create and manage user roles to hspp group

- keycloak-test/realms/moh_applications/clients/forms/main.tf
Add missing Redirect URIs for SiteMinder + PHSA logout to FORMS.
FORMS has SiteMinder + PHSA integrations and the logontest7.gov.bc.ca + sts.healthbc.org URIs must be added for chained logout to work.
 
> Add missing Redirect URIs for SiteMinder + PHSA logout

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/dhiper/main.tf
- keycloak-test/realms/moh_applications/clients/dhiper/outputs.tf
- keycloak-test/realms/moh_applications/clients/dhiper/versions.tf
Creating DHIPER client on Keycloak Test environment. As for now, the client defines three roles and two mappers: role + IDIR.
The `dhiper.hlth.gov.bc.ca` URL was omitted from valid redirect URLs for now, as it seems it's Prod URL. Will follow up with the DHIPER team. `localhost` urls were added for development purpouses.
DHIPER is new application, and will be used to enable Ministry of Health users, specifically in the Digital Investment, Governance & Transformation (DIGT) branch access to the portal being developed by the Data Warehouse Services team.
Architecture-wise client is similar to HSPP.
 
[^1]: Data transparency. Does the client you are creating have the permissions to pass/access all the Client Scope attributes in the token? For example `profile` scope includes user birthdate, …
> dhiper test client

- .github/pull_request_template.md
- keycloak-test/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-test/realms/moh_applications/clients/user-management/main.tf
- keycloak-test/realms/moh_applications/groups.tf
- keycloak-test/realms/moh_applications/groups/dhiper-management/main.tf
- keycloak-test/realms/moh_applications/groups/dhiper-management/output.tf
- keycloak-test/realms/moh_applications/groups/dhiper-management/variables.tf
- keycloak-test/realms/moh_applications/groups/dhiper-management/versions.tf
- keycloak-test/realms/moh_applications/realm-roles/manage-users/main.tf
Creating DHIPER management group on test env. The permissions are similar to HSPP Admin group.
Added `view-client-dhiper` role to UMC/UMS.
The group will allow DHIPER team to manage authorization through UMC.
 
> create dhiper test admin group

- keycloak-dev/realms/moh_applications/clients.tf
- keycloak-dev/realms/moh_applications/clients/metaspace/main.tf
- keycloak-dev/realms/moh_applications/clients/metaspace/outputs.tf
- keycloak-dev/realms/moh_applications/clients/metaspace/versions.tf
Adding new METASPACE Dev client for Keycloak Dev
METASPACE is a Drupal application looking to be onboarded. See [AB#10473 - Add Dev METASPACE client configuration to Keycloak Dev](https://dev.azure.com/cgi-vic-hlth/AM%20Team/_workitems/edit/10473) for more details.
[^2]:
Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not interfere with existing …
> Adding new METASPACE Dev client for Keycloak Dev

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/ehpr/main.tf
- keycloak-test/realms/moh_applications/clients/ehpr/outputs.tf
- keycloak-test/realms/moh_applications/clients/ehpr/versions.tf
Created EHPR client with org_details mapper.
EHPR is the Emergency Health Provider Registry. Health workers can sign up at https://ehpr.gov.bc.ca/. In times of flood, earthquake, or wildfire, registrants may be called up to help.
[^2]:
Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not interfere with existing configuration, they can be ignored. Here is …
> create ehpr test client

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/usam/main.tf
- keycloak-test/realms/moh_applications/clients/usam/outputs.tf
- keycloak-test/realms/moh_applications/clients/usam/versions.tf
Create a basic USAM client on the test environment with IDIR username and display name mappers. The valid redirect URLs still need to be specified by the client. As for now, for development purposes, the valid redirect URLs are set to localhost.
[^2]:
Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not interfere with existing configuration, they can be …
> create usam test client

- keycloak-dev/realms/moh_applications/clients.tf
- keycloak-dev/realms/moh_applications/clients/hlbc/main.tf
- keycloak-dev/realms/moh_applications/clients/hlbc/outputs.tf
- keycloak-dev/realms/moh_applications/clients/hlbc/variables.tf
- keycloak-dev/realms/moh_applications/clients/hlbc/versions.tf
- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/hlbc/main.tf
- keycloak-test/realms/moh_applications/clients/hlbc/outputs.tf
- keycloak-test/realms/moh_applications/clients/hlbc/variables.tf
- keycloak-test/realms/moh_applications/clients/hlbc/versions.tf
Adding dev and test config for onboarding HealthLink BC as a client
HealthLink BC wishes to use OIDC for authentication
> 10417-Client Onboarding - HealthLink BC: adding dev and test config

- keycloak-test/realms/moh_applications/clients/ehpr/main.tf
Adding redirect URLs for EHPR client on the Test environment.
EHPR requires IDIR and Health Authorities login.
> add redirect uris for ehpr

- keycloak-dev/realms/moh_applications/clients/metaspace/main.tf
Adding IDP mapper as username based parsing isn't ideal (HAs).
Metaspace needs to be able to determine if users are coming in from IDIR, HA, or BCeID IDPs.
[^1]:
> Adding IDP mapper as username based parsing isn't ideal (HAs)

- keycloak-dev/realms/moh_applications/clients/metaspace/main.tf
Add `identity_provider` to id token on METASPACE Dev client
Drupal applications only really care about the id token since roles are managed through the application, so having `identity_provider` only available through the access token (where we normally put it) isn't ideal for them.
[^1]:
> Add identity_provider to id token on METASPACE Dev client

- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/plr-shoppers/main.tf
- keycloak-prod/realms/moh_applications/clients/plr-shoppers/outputs.tf
- keycloak-prod/realms/moh_applications/clients/plr-shoppers/variables.tf
- keycloak-prod/realms/moh_applications/clients/plr-shoppers/versions.tf
Creating PLR-SHOPPERs client on prod environment. The PLR team specified the org as 00024727 in their request. The rest of the config is as in PLR-SHOPPERS on test environment. 
[^2]:
[^3]: Due to the terraform provider …
> create plr-shoppers prod client

- keycloak-dev/realms/moh_applications/clients/metaspace/main.tf
Adding `bceid_business_legalName` mapper for METASPACE Dev.
Hemant has requested the `bceid_business_legalName` attribute be mapped similar to the `idir_company` on METASPACE Dev.
[^1]:
> Adding bceid_business_legalName mapper for METASPACE Dev

- keycloak-prod/realms/moh_applications/groups/hspp-management/main.tf
- keycloak-test/realms/moh_applications/groups/hspp-management/main.tf
Granting HSPP admin group access to UMC dashboard in prod and test, so they can see login statistics.
> grant-umc-dashboard-access-to-hspp

- keycloak-test/realms/moh_applications/clients/hem/main.tf
Adding localhost Redirect URIs to HEM Test.
I can't connect from my localhost.
[^1]:
> Add localhost to HEM Test

- keycloak-dev/realms/moh_applications/clients/forms/main.tf
- keycloak-prod/realms/moh_applications/clients/forms/main.tf
- keycloak-test/realms/moh_applications/clients/forms/main.tf
Adding IDP mapper for FORMS (like METASPACE).
Mael has requested we add the IDP mapper to all FORMS clients, mirroring what was done for Hemant on the METASPACE clients.
> Adding IDP mapper for FORMS (like METASPACE)

- keycloak-prod/realms/moh_applications/clients/ppm-api-cgi-BC30550160/main.tf
Remvoed defaulted mappers.
"Client Host", "Client ID" and "Client IP Address" mappers get created by default on client creation so explicitly defining them is unnecessary and caused an error in Terraform
> remvoed defaulted mappers

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/lra-dev/main.tf
- keycloak-test/realms/moh_applications/clients/lra-dev/outputs.tf
- keycloak-test/realms/moh_applications/clients/lra-dev/variables.tf
- keycloak-test/realms/moh_applications/clients/lra-dev/versions.tf
- keycloak-test/realms/moh_applications/clients/lra-sandbox/main.tf
- keycloak-test/realms/moh_applications/clients/lra-sandbox/outputs.tf
- keycloak-test/realms/moh_applications/clients/lra-sandbox/variables.tf
- keycloak-test/realms/moh_applications/clients/lra-sandbox/versions.tf
- keycloak-test/realms/moh_applications/clients/lra-test/main.tf
- keycloak-test/realms/moh_applications/clients/lra-test/outputs.tf
- keycloak-test/realms/moh_applications/clients/lra-test/variables.tf
- keycloak-test/realms/moh_applications/clients/lra-test/versions.tf
Creating 3 clients for LRA (Dev, Test, Sandbox) on the Keycloak Test environment. For now, each client has `localhost` configured as valid redirect URLs. This configuration will be updated once we know more details. 
Each client has a client role mapper defined, that allows to pass roles from LICENSE-STATUS inside a token.
LRA is an application that allows users to access Longitudinal Health Records. 
CMDB is not updated yet.
[^2]:
Keep in mind that sometimes Keycloak automatically adds properties to newly created …
> create lra non-prod clients

- keycloak-test/realms/moh_applications/clients/prp-service/main.tf
- keycloak-test/realms/moh_applications/clients/prp-web/main.tf
Adding administrator role to PRP-SERVICE. Updating PRP-WEB scopes, so the new role shows up in the token. Sorted the roles alphabetically.
> add HI_ADMINISTRATOR role to PRP

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/tbcm/main.tf
- keycloak-test/realms/moh_applications/clients/tbcm/outputs.tf
- keycloak-test/realms/moh_applications/clients/tbcm/versions.tf
Create basic confidential client for TBMC on test environment.
New client onboarding. Team Based Care Manager (TBCM) is a new application that allows team leads to plan out shift assignments.
[^2]:
[^3]: Due to the …
> create tbcm test client

- keycloak-dev/realms/moh_applications/clients/hlbc/main.tf
- keycloak-test/realms/moh_applications/clients/hlbc/main.tf
Adding mappers to dev and test:
- identity_provider
- idir_company
HLBC requires these mappers for their client.
> Added required mappers

- keycloak-test/realms/moh_applications/clients/prp-web/main.tf
Adding role mapper to PRP-WEB on Test environment.
PRP-WEB wants to have it's roles passed in "roles" claim, not in "resource-access" claim, to follow the architectural patterns of HSPP and DHIPER.
> add role mapper for prp-web on test

- keycloak-test/realms/moh_applications/clients/ehpr/main.tf
Allowing CORS from domains included in the valid redirect URLs section. Adding localhost as valid redirect URL.
EHPR team reported CORS issues.
[^2]:
> enable CORS and add redirect URL for EHPR client

- keycloak-test/realms/moh_applications/clients/hcap-fe/main.tf
Adding new role "mhsu-employer" to HCAP client
HCAP requires the new role "mhsu-employer"
> HCAP: added role in test

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/prp-web/main.tf
- keycloak-test/realms/moh_applications/clients/prp-web/variables.tf
PRP-WEB client changes: adding redirect URL, configuring a mapper to include LICENCE-STATUS in ID Token. Including CPN and IDP in the ID Token.
PRP-WEB needs those attributes to comply with new architecture changes.
> pass licence status to prp-web on test

- keycloak-prod/realms/moh_applications/clients/sat-eforms/main.tf
- keycloak-test/realms/moh_applications/clients/sat-eforms/main.tf
Adding a role to SAT-EFORMS on test and prod environment. 
New role in SAT-EFORMS. PIDP service account needs the ability to assign this role. This was previously ensured, by adding UMS roles: `view-client-sat-eforms` and `manage-user-roles` to the service account.
> create sat-eforms role test and prod

- keycloak-test/realms/moh_applications/clients/gis/main.tf
Adding new GIS Test redirect_uri.
A new AWS redirect_uri for GIS Test is required by the Cloud Migration project.
[^1]:
> Adding new GIS Test redirect_uri

- keycloak-test/realms/moh_applications/clients/prp-web/main.tf
Setting the type of PRP-WEB client as confidential. The other settings, such as `service-accounts enabled` were derived from DHIPER and HSPP clients. Those applications follow the same architecture pattern.
PRP-WEB & CLIIP architecture changes.
> Change prp web confidentiality

- keycloak-prod/realms/moh_applications/clients/dmft-webapp/main.tf
- keycloak-prod/realms/moh_applications/clients/pidp-webapp/main.tf
- keycloak-prod/realms/moh_applications/clients/prime-application/main.tf
- keycloak-prod/realms/moh_applications/clients/prime-webapp-enrollment/main.tf
Adding birthdate mappers to clients who use DOB.
in preparation to remove "birthdate" from profile scope in Prod env.
> add birthdate mappers to prod clients

- keycloak-test/realms/moh_applications/clients/lra-dev/main.tf
- keycloak-test/realms/moh_applications/clients/lra-sandbox/main.tf
- keycloak-test/realms/moh_applications/clients/lra-test/main.tf
Add LICENCE-STATUS scope mapping to LRA clients so that LICENCE-STATUS is included in the tokens.
The LICENCE-STATUS protocol mapper was added, but we forgot to include the scope mappings. This caused an issue.
> LRA clients: Add Licence Status scope mapping.

- keycloak-prod/realms/moh_applications/groups/prime-management/main.tf
Removing `view-client-primary-care` from PRIME-MANAGEMENT group.
By mistake, `view-client-primary-care` role was added to PRIME-MANAGEMENT. It gives the members of the group more privileges than they should have.
> remove primary-care role from prime management group

- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Updated HSPP redirect_uris. Added new UAT URL and removed existing STG URL.
Change requested by DMS.
[^2]:
[^3]: Due to the terraform provider bug, updating/deleting one entry within the resource deletes all of them. …
> Updated redirect_uris for HSPP in Test.

- keycloak-test/realms/moh_applications/clients/tbcm/main.tf
- keycloak-test/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-test/realms/moh_applications/clients/user-management/main.tf
- keycloak-test/realms/moh_applications/groups.tf
- keycloak-test/realms/moh_applications/groups/tbcm-management/main.tf
- keycloak-test/realms/moh_applications/groups/tbcm-management/output.tf
- keycloak-test/realms/moh_applications/groups/tbcm-management/variables.tf
- keycloak-test/realms/moh_applications/groups/tbcm-management/versions.tf
On test environment: 
1. Add an `admin` role to TBCM client.
2.  Create a `tbcm-management` group. This group will allow for TBCM role assignment through UMC. 
TBCM client onboarding request
> add tbcm role and group

- keycloak-test/realms/moh_applications/groups/tbcm-management/main.tf
Fix TBCM admin group name
I've made a mistake and copied over the wrong group name which results in 409 - conflict error when applying the changes to terraform.
> Create tbcm admin group

- keycloak-dev/realms/moh_applications/clients/pidp-webapp/main.tf
Adding birthdate mapper to pidp-webapp on dev environment.
The reason for this PR is just to keep consistency between dev/test/prod environments. The birthdate has been already removed from the `profile` scope both on test and prod environments. Adding a custom birthdate mapper to the pidp-webapp client is a pre-work for removing the `birthdate` from the dev environment. 
The work was only done on test & prod before, as dev env is a sandbox for the Keycloak team and the affected clients were not actively using dev enviornment.
> create birthdate mapper for pidp

- keycloak-test/realms/moh_applications/clients/prp-web/main.tf
Adding new redirect uri for PRP-WEB to Keycloak Test.
Updated requested by DMS.
[^2]:
[^3]: Due to the terraform provider bug, updating/deleting one entry within the resource deletes all of them. Re-running the `apply` …
> Added redirect URI for PRP-WEB

- keycloak-test/realms/moh_applications/realm-roles/manage-users/main.tf
Updating `manage-users` realm role on test environment
updating the manage-users role will allow Keycloak developers to assign TBCM client roles.
> add view-client-tbcm role to manage-users realm role

- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/tbcm/main.tf
- keycloak-prod/realms/moh_applications/clients/tbcm/outputs.tf
- keycloak-prod/realms/moh_applications/clients/tbcm/versions.tf
Creating TBMC client on Prod environment
TBCM team is preparing to move to production. The client is identical as in test, apart from the redirect URL. The current one points to the CloudFront. This will be changed in the near future once the TBCM team resolves domain & certificate requests.
[^2]:
Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not …
> create tbcm client on prod environment

- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Add a user attribute mapper for the HSPP client in TEST to add the idir_mailboxOrgCode to the ID token.
HSPP has requested this attribute. They will use it for authorization.
> HSPP: Add idir_mailboxOrgCode user attribute mapper.

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/plr-lra/main.tf
- keycloak-test/realms/moh_applications/clients/plr-lra/variables.tf
Add PLR_IAT as an environment to existing PLR-LRA client.
Kim Glidden has requested we attempt to re-use the existing PLR-LRA client already in use with the PLR_REV environment.
[^1]:
[^2]: Due to the terraform provider bug, updating/deleting one entry within the resource deletes all of them. Re-running the `apply` action will result in restoring the configuration to the desired state. Keep in mind, that `composite role` deletion will show up on the `terraform plan` output, on contrary to `scope …
> Changes requested by Kim Glidden

- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/ehpr/main.tf
- keycloak-prod/realms/moh_applications/clients/ehpr/outputs.tf
- keycloak-prod/realms/moh_applications/clients/ehpr/versions.tf
Creating the EHPR client on prod. The client has the same configuration as on Test environment. 
EHPR is preparing to update/release on Production environment
[^2]:
[^3]: Due to the terraform provider bug, …
> promote ehpr client to prod

- keycloak-test/realms/moh_applications/clients/emcod/main.tf
Adding redirect URL to EMCOD client on test environment. Removing the URL from web_origins section as `+` already includes this URL. (`+` includes all URLs specified in the valid_redirect_section)
> add redirect url to test emcod client

- keycloak-test/realms/moh_applications/clients/lra-dev/main.tf
- keycloak-test/realms/moh_applications/clients/lra-sandbox/main.tf
- keycloak-test/realms/moh_applications/clients/lra-test/main.tf
Adding redirect URLs to LRA-Dev/Sandbox/Test clients on Keycloak test environment.
> add lra redirect urls

- keycloak-dev/realms/moh_applications/clients/metaspace/main.tf
Adding Metaspace mappers for idir_displayName + idir_mailboxOrgCode as per Hemant Kumar.
HLTH IDIR users need to be able to be identified for Metaspace authorization as they had been historically through SiteMinder's groups attribute.
[^1]:
> Adding Metaspace IDIR attribute mappers

- keycloak-test/realms/moh_applications/clients/plr-wava/main.tf
Changing the plr-wava client references. PLR_IAT role definition was pointing at PLR_REV client. 
[^2]:
[^3]: Due to the terraform provider bug, updating/deleting one entry within the resource deletes all of them. Re-running the `apply` action will result in restoring the configuration to the desired state. Keep in mind, that `composite role` deletion will show up on the `terraform plan` output, on contrary to `scope mapping`.
> fix wava client references

- keycloak-prod/realms/moh_applications/clients/tbcm/main.tf
- keycloak-test/realms/moh_applications/clients/tbcm/main.tf
TBCM client: adding `user` role on test and prod environment. Adding redirect URL on Prod.
TBCM is preparing for PROD release. The cloudfront URL will be deleted when the changes are confirmed.
> update roles and url for tbcm

- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/moh-splunk/main.tf
- keycloak-prod/realms/moh_applications/clients/moh-splunk/outputs.tf
- keycloak-prod/realms/moh_applications/clients/moh-splunk/versions.tf
What is the context for those changes? For example: particular role needs to be shown in token. Reference Azure Board task, if applicable.
[^2]:
[^3]: Due to the terraform …
> Migrating splunk client to prod

- keycloak-test/realms/moh_applications/clients/tbcm/main.tf
TBCM would like to have their application roles included in access and ID tokens, as well as /userinfo endpoint reply
> adding role mapper to include roles in userinfo

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/dht-dev/main.tf
- keycloak-test/realms/moh_applications/clients/dht-dev/outputs.tf
- keycloak-test/realms/moh_applications/clients/dht-dev/variables.tf
- keycloak-test/realms/moh_applications/clients/dht-dev/versions.tf
On KC Test environment, create DHT-DEV client. Essentially, a copy of the LRA-TEST client.
Cleaned up the whitespaces from clients.tf file
Brad Head request. Part of the LRA integration. DHT-DEV might get merged later into LRA clients.
[^2]:
Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not interfere with existing configuration, they can be ignored. …
> create dht-dev client and cleanup clients.tf whitespaces

- keycloak-test/realms/moh_applications/clients/primary-care/main.tf
Adding hardcoded role mapper for PRIMARY-CARE on test.
PRIMARY-CARE wants to assign role by default to each user.
> add hardocoded role mapper

- keycloak-dev/realms/moh_applications/clients/pidp-service-account/main.tf
- keycloak-test/realms/moh_applications/clients/pidp-service-account/main.tf
Adding `aud` and `resource_access` claim mappers to PIDP-SERVICE-ACCOUNT client on dev and test env
Request from James Hollinger - `service_account` role should show up under PIDP-SERVICE, although it's defined in PIDP-SERVICE-ACCOUNT client. Adding it directly to PIDP-SERVICE is not an option as it would show up in UMC, hence the mapper.
> add custom mappers to pidp-service-account

- keycloak-prod/realms/moh_applications/clients/hcap-fe/main.tf
Adding new role "mhsu-employer" to HCAP client in prod.
HCAP requires the new role "mhsu-employer" to be available in prod.
> HCAP: added role in prod

- keycloak-test/realms/moh_applications/clients/hsiar/main.tf
Adding localhost as redirect URL to HSIAR client on test env
> add localhost redirect to hsiar on test

- keycloak-dev/realms/moh_applications/clients/pidp-service-account/main.tf
- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/pidp-service-account/main.tf
- keycloak-prod/realms/moh_applications/clients/pidp-service-account/outputs.tf
- keycloak-prod/realms/moh_applications/clients/pidp-service-account/versions.tf
- keycloak-test/realms/moh_applications/clients/pidp-service-account/main.tf
Creating pidp-service-account client on Prod environment. Copy of client on dev/test environments. Used for internal api calls authorization.
Adding names to clients on dev/test.
> Create pidp service account in prod

- keycloak-dev/realms/moh_applications/clients/prp-web/main.tf
Adding https://moh-dms-m-dev-as-prpcliip.azurewebsites.net/* to PRP-WEB Dev client.
Adding PRP-WEB Dev Redirect URI as per Paul Kulpas.
[^1]:
> Adding PRP-WEB Dev Redirect URI

- keycloak-test/realms/moh_applications/clients/usam/main.tf
Adding idir_user_guid mapper to USAM client on test
Request from Jason Platt
> add usam idir guid mapper

- keycloak-test/realms/moh_applications/groups/itsb-access-team/main.tf
Add view-client-icy to ITSB admin group
> allow itsb to manage icy client

- keycloak-prod/realms/moh_applications/clients/hspp/main.tf
- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Added HSPP_Restricted_CVC role to HSPP in Test and Prod.
Requested by DMS.
[^2]:
[^3]: Due to the terraform provider bug, updating/deleting one entry within the resource deletes all of them. Re-running the `apply` action …
> Added HSPP_Restricted_CVC role to Test and Prod.

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/plr-prp/main.tf
- keycloak-test/realms/moh_applications/clients/plr-prp/variables.tf
Assigning CONSUMER role to plr-prp client on Keycloak Test environment.
Kushwinder (PLR) confirmed that org-id will be the same across REV and IAT environments.
> assign plr-iat role

- keycloak-prod/realms/moh_applications/clients/gis/main.tf
- keycloak-prod/realms/moh_applications/clients/hspp/main.tf
- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Add a role to HSPP on test and prod env. Add GIS redirect url on Prod, to persist the manual changes.
> add hspp role and persist gis url

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/cmdb/main.tf
- keycloak-test/realms/moh_applications/clients/cmdb/outputs.tf
- keycloak-test/realms/moh_applications/clients/cmdb/versions.tf
This change includes the addition of the new client configuration for CMDB
This is needed for migrating CMDB away from LDAP
[^2]:
[^3]: Due to the terraform provider bug, updating/deleting one entry within the resource …
> Added client for CMDB test

- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Replace sithspp.healthideas.gov.bc.ca with sithspp.hlth.gov.bc.ca in Test.
Change requested by HSIAR via AM inbox request.
[^2]:
> Update HSPP Redirect URIs in Test

- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/alr/main.tf
- keycloak-prod/realms/moh_applications/clients/alr/outputs.tf
- keycloak-prod/realms/moh_applications/clients/alr/versions.tf
- keycloak-prod/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-prod/realms/moh_applications/clients/user-management/main.tf
- keycloak-prod/realms/moh_applications/groups.tf
- keycloak-prod/realms/moh_applications/groups/alr-management/main.tf
- keycloak-prod/realms/moh_applications/groups/alr-management/output.tf
- keycloak-prod/realms/moh_applications/groups/alr-management/variables.tf
- keycloak-prod/realms/moh_applications/groups/alr-management/versions.tf
- keycloak-test/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-test/realms/moh_applications/clients/user-management/main.tf
- keycloak-test/realms/moh_applications/groups.tf
- keycloak-test/realms/moh_applications/groups/alr-management/main.tf
- keycloak-test/realms/moh_applications/groups/alr-management/output.tf
- keycloak-test/realms/moh_applications/groups/alr-management/variables.tf
- keycloak-test/realms/moh_applications/groups/alr-management/versions.tf
Promoting ALR client to Production environment. Crating ALR-MANAGEMENT group on Test and Production environment.
> create alr prod client and management groups

- keycloak-dev/realms/moh_applications/clients.tf
- keycloak-dev/realms/moh_applications/clients/hcim_lra/main.tf
- keycloak-dev/realms/moh_applications/clients/hcim_lra/outputs.tf
- keycloak-dev/realms/moh_applications/clients/hcim_lra/versions.tf
- keycloak-dev/realms/moh_applications/clients/hcimweb/main.tf
- keycloak-dev/realms/moh_applications/clients/hcimweb_hd2/main.tf
Adding HCIM_LRA client on dev environment. Exact copy of client from TEST.
Changing theme explicitly set on HCIMWEB clients on dev.
HCIM_LRA is a service account that allows for communication between HCIM and LRA systems.
> Create hcim lra on dev

- keycloak-dev/main.tf
- keycloak-dev/realms/moh_applications/clients/terraform/main.tf
DEV: Configure Terraform to use a service account in the master realm instead of moh_applications so that it can manage clients in multiple realms.
This will allow Terraform to manage clients in multiple realms. We would like to use Terraform to manage clients in the new "applications" realm.
> DEV: Configure Terraform to use a service account in the master realm

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/health-ideas/main.tf
- keycloak-test/realms/moh_applications/clients/health-ideas/outputs.tf
- keycloak-test/realms/moh_applications/clients/health-ideas/versions.tf
- keycloak-test/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-test/realms/moh_applications/clients/user-management/main.tf
- keycloak-test/realms/moh_applications/groups.tf
- keycloak-test/realms/moh_applications/groups/health-ideas-management/main.tf
- keycloak-test/realms/moh_applications/groups/health-ideas-management/output.tf
- keycloak-test/realms/moh_applications/groups/health-ideas-management/variables.tf
- keycloak-test/realms/moh_applications/groups/health-ideas-management/versions.tf
- keycloak-test/realms/moh_applications/realm-roles/manage-users/main.tf
Creating Health Ideas client on Test and management groups for it.
New client onboarding. 'terraform apply' will need to be re-run since composite role is being updated.
[^2]:
[^3]: Due to the terraform provider bug, …
> configure health-ideas client and management groups

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/panorama/main.tf
- keycloak-test/realms/moh_applications/clients/panorama/outputs.tf
- keycloak-test/realms/moh_applications/clients/panorama/versions.tf
What is the context for those changes? For example: particular role needs to be shown in token. Reference Azure Board task, if applicable.
[^2]:
[^3]: Due to the terraform …
> Add Panorama to TEST.

- keycloak-test/realms/moh_applications/clients/panorama/main.tf
Fix web-origins value. Cannot be empty string.
The previous PR `apply` failed due to this mistake, so this will include adding the Panorama client to TEST.
> PANAORAMA TEST: Fix web-origins value. Cannot be empty string.

- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/plr-regadmin/main.tf
- keycloak-prod/realms/moh_applications/clients/plr-regadmin/outputs.tf
- keycloak-prod/realms/moh_applications/clients/plr-regadmin/variables.tf
- keycloak-prod/realms/moh_applications/clients/plr-regadmin/versions.tf
Create service account for PLR on Prod with REGADMIN role.
> create plr-regadmin service account on prod

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/plr-lra-regadmin/main.tf
- keycloak-test/realms/moh_applications/clients/plr-lra-regadmin/outputs.tf
- keycloak-test/realms/moh_applications/clients/plr-lra-regadmin/variables.tf
- keycloak-test/realms/moh_applications/clients/plr-lra-regadmin/versions.tf
Creating a service account client for LRA that will allow them to call PLR with REGADMIN permissions.
> create plr-lra-regadmin client on test

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/phlat/main.tf
- keycloak-test/realms/moh_applications/clients/phlat/outputs.tf
- keycloak-test/realms/moh_applications/clients/phlat/versions.tf
- keycloak-test/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-test/realms/moh_applications/clients/user-management/main.tf
- keycloak-test/realms/moh_applications/groups.tf
- keycloak-test/realms/moh_applications/groups/phlat-management/main.tf
- keycloak-test/realms/moh_applications/groups/phlat-management/output.tf
- keycloak-test/realms/moh_applications/groups/phlat-management/variables.tf
- keycloak-test/realms/moh_applications/groups/phlat-management/versions.tf
- keycloak-test/realms/moh_applications/realm-roles/manage-users/main.tf
Create PHLAT basic client + management groups to allow UMC access.
New Client Onboarding
[^2]:
[^3]: Due to the terraform provider bug, updating/deleting one entry within the resource deletes all of them. Re-running the …
> create phlat client and management groups

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/health-ideas-apex/main.tf
- keycloak-test/realms/moh_applications/clients/health-ideas-apex/outputs.tf
- keycloak-test/realms/moh_applications/clients/health-ideas-apex/versions.tf
Create HealthIdeas APEX client.
[^2]:
[^3]: Due to the terraform provider bug, updating/deleting one entry within the resource deletes all of them. Re-running the `apply` action will result in restoring the configuration …
> create health-ideas-apex client

- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Add redirect URL for hspp on Keycloak Test env.
> add hssp redirect url

- keycloak-test/realms/moh_applications/clients/cmdb/main.tf
What is the context for those changes? For example: particular role needs to be shown in token. Reference Azure Board task, if applicable.
[^2]:
[^3]: Due to the terraform …
> Added temporary nimbus URL for pre-cutover testing

- keycloak-test/realms/moh_applications/clients/dht-dev/main.tf
Temporarily allow wildcard directs for this client.
Brad Head has requested to re-purpose this client. We will tighten redirects later.
[^2]:
[^3]: Due to the terraform provider bug, updating/deleting one entry within the …
> DHT-DEV: Wildcard redirects.

- keycloak-test/realms/moh_applications/clients/health-ideas-apex/main.tf
- keycloak-test/realms/moh_applications/clients/health-ideas/main.tf
Whitelisting URLS for HealthIdeas applications
Both applications reside under the same domain.
> update health-ideas urls

- keycloak-prod/realms/moh_applications/clients/prp-web/main.tf
- keycloak-test/realms/moh_applications/clients/phlat-web/main.tf
- keycloak-test/realms/moh_applications/clients/prp-web/main.tf
CORS changes, client name changes
> rename clients, fix phlat mapper, persist web origins

- keycloak-dev/realms/moh_applications/clients/metaspace/main.tf
Adding/removing valid redirect URIs to Metaspace Dev client configuration
Development on Metaspace has started back up in a push to have it completed by end of fiscal.
[^1]:
> Adding/removing valid redirect URIs to Metaspace Dev client configuration

- keycloak-dev/realms/moh_applications/groups/itsb-access-team/main.tf
- keycloak-prod/realms/moh_applications/groups/itsb-access-team/main.tf
Updating ITSB Access Team group in Keycloak Dev/Prod.
David Arnatt is requesting Keycloak group configuration updates and user roles removed from existing users for the PHO-RSC client in Production.
[^1]:
> Updating ITSB Access Team group in Keycloak Dev/Prod

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/metaspace/main.tf
- keycloak-test/realms/moh_applications/clients/metaspace/outputs.tf
- keycloak-test/realms/moh_applications/clients/metaspace/versions.tf
Add Metaspace Stg (Test) client for Hemant.
Metaspace needs a Staging client setup in the Keycloak Test environment. They don't have an existing Test client and don't have plans for one, so we're not going through with a _STG client.
[^2]:
Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not interfere with existing configuration, they can be ignored. Here …
> Add Metaspace Stg (Test) client for Hemant

- .github/workflows/terraform.yml
Updating GitHub Actions: actions/checkout@v3, hashicorp/setup-terraform@v2, actions/github-script@v6
[Terraform](https://github.com/bcgov/moh-keycloak-client-configurations/actions/runs/8367023478/job/22908530378)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, hashicorp/setup-terraform@v2, actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> bump action versions

- keycloak-prod/realms/moh_applications/groups/itsb-access-team/main.tf
- keycloak-test/realms/moh_applications/groups.tf
- keycloak-test/realms/moh_applications/groups/cgi-salesforce/main.tf
- keycloak-test/realms/moh_applications/groups/cgi-salesforce/output.tf
- keycloak-test/realms/moh_applications/groups/cgi-salesforce/variables.tf
- keycloak-test/realms/moh_applications/groups/cgi-salesforce/versions.tf
Creating CGI-Salesforce access management group on Test environment. Updating ITSB permissions.
> create cg-salesforce group in test, update itsb permissions

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/hcim_fha_dfd/main.tf
- keycloak-test/realms/moh_applications/clients/hcim_fha_dfd/outputs.tf
- keycloak-test/realms/moh_applications/clients/hcim_fha_dfd/versions.tf
Create new service account from HCIM on test env: HCIM_FHA_DFD (Fraser Health Authority - Digital Front Door).
The template for this client is HCIM_LRA.
Service account - no client name
> create hcim-fha-dfd test client

- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/hcimweb_hs1/main.tf
- keycloak-prod/realms/moh_applications/clients/hcimweb_hs1/outputs.tf
- keycloak-prod/realms/moh_applications/clients/hcimweb_hs1/versions.tf
- keycloak-prod/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-prod/realms/moh_applications/clients/user-management/main.tf
- keycloak-prod/realms/moh_applications/realm-roles/manage-users/main.tf
Copying HCIMWEB_HS1 client to Production environment. Add `view-client-hcimweb_hs1` role to UMC and scope mapping to UMC to allow managing roles for this client through User Management Console. Add `view-client-hcimweb_hs1` to ManageUsers realm role.
HCIM team wants to connect their staging environment to Keycloak Production. HCIMWEB_HS1 client on test is kept intact in case rollback is needed.
Terraform apply will likely need to be re-run as composite role is being updated.
> create hcimweb_hs1 client on prod, update ums and realm roles

- keycloak-prod/realms/moh_applications/clients/hsiar/main.tf
- keycloak-test/realms/moh_applications/clients/hsiar/main.tf
Recreate HSIAR roles using new names.
> Hi Keycloak team,
> 
> Can you help to rename these roles below in the Test environment?
> Existing role name	New role name
> HI_Consumer	HI_SUPPORT_ROLE
> HI_ReportSection_All	HI_SUPPORT_ROLE_SECTION
> HI_ReportProgram_All	HI_SUPPORT_ROLE_PROGRAM
> 
> I believe these roles does not exist in Prod yet. But if they are, please help to rename the Prod version too.
> Sri
Sri has acknowledged that users with these roles currently assigned will lose the roles. They will need to be manually reassigned by Sri.
No one is currently assigned the roles in PROD. 14 users are assigned various HSIAR roles in TEST.
> Recreate HSIAR roles with new names

- keycloak-prod/realms/moh_applications/clients/health-ideas-apex/main.tf
- keycloak-prod/realms/moh_applications/clients/health-ideas/main.tf
- keycloak-test/realms/moh_applications/clients/health-ideas-apex/main.tf
- keycloak-test/realms/moh_applications/clients/health-ideas/main.tf
Update HEALTH-IDEAS redirect URLs in TEST and PROD
> For both our applications (HEALTH-IDEAS-APEX and HEALTH-IDEAS ) we currently have the following  URLs:
>  
> TEST keycloak:
> https://devsecure.healthideas.gov.bc.ca/<anyurl>
> https://uatsecure.healthideas.gov.bc.ca/<anyurl>
> https://devsecuret.healthideas.gov.bc.ca/<anyurl>
> https://uatsecuret.healthideas.gov.bc.ca/<anyurl>
> https://localhost:<anyport>/<anyurl>
> 
> PROD:
> https://secure.healthideas.gov.bc.ca/<anyurl>
> https://securet.healthideas.gov.bc.ca/<anyurl>
> 
> 
> Can you please add the following URLs to the configuration?
> 
> TEST keycloak:
> uatexternal.healthideas.gov.bc.ca/<anyurl>
> uatexternalt.healthideas.gov.bc.ca/<anyurl>
> 
> PROD:
> external.healthideas.gov.bc.ca/<anyurl>
> …
> Update HEALTH-IDEAS redirect URLs in TEST and PROD

- keycloak-dev/realms/moh_applications/clients.tf
- keycloak-dev/realms/moh_applications/clients/pho-rsc-groups/main.tf
- keycloak-dev/realms/moh_applications/clients/pho-rsc-groups/outputs.tf
- keycloak-dev/realms/moh_applications/clients/pho-rsc-groups/versions.tf
- keycloak-dev/realms/moh_applications/clients/pho-rsc/main.tf
- keycloak-dev/realms/moh_applications/clients/pho-rsc/variables.tf
- keycloak-dev/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-dev/realms/moh_applications/groups/pho-rsc-management/main.tf
- keycloak-dev/realms/moh_applications/groups/pho-rsc-management/output.tf
- keycloak-dev/realms/moh_applications/groups/pho-rsc-management/variables.tf
- keycloak-dev/realms/moh_applications/groups/pho-rsc-management/versions.tf
Create PHO-RSC-GROUPS bearer-only client on DEV and set-up UMC/UMS management.
Included changes:
* Set-up new bearer-only client to hold roles specified by development team.
* Add scope mappings to existing client.
* Set-up UMC/UMS to enable management of new client.
* Copy PROD PHO-RSC group to development for testing. Add new client.
The PHO-RSC development team has requested a separate client to manage a seperate set of roles, that they call "groups."
[^2]:
Keep in mind that sometimes Keycloak automatically …
> Create PHO-RSC-GROUPS bearer-only client on DEV

- keycloak-test/realms/moh_applications/clients/phlat-web/main.tf
PHLAT-WEB (TEST): Increase token lifespan to two hours to allow ZAP scan to complete
PHLAT-WEB developer requests changes.
> PHLAT-WEB (TEST): Increase token lifespan to two hours to allow ZAP scan to complete

- keycloak-test/realms/moh_applications/clients/plr-cpsbc/main.tf
PLR-CPSBC (TEST): Specify client ID format in the token.
PLR-ESB looks for the client ID in the token in a specific format. The Keycloak default used to match the intended format, but Keycloak 20 changed it to client_id to be more specification compliant.
> PLR-CPSBC (TEST): Specify client ID format in the token.

- keycloak-dev/events.tf
Remove mhsu_ehs event configuration because realm is disabled
Realm is being decomissioned.
> Remove mhsu_ehs event configuration because realm is disabled

- keycloak-prod/realms/moh_applications/clients/metaspace/main.tf
Add temporary URL for pre-cutover testing.
Mid-Tier requries a temporary valid redirect URI added for Metaspace Prod to test the application pre-cutover.
[^1]:
> Update Metaspace Prod client redirects

- keycloak-dev/realms/moh_applications/clients/bcer-cp/main.tf
- keycloak-dev/realms/moh_applications/clients/connect/main.tf
- keycloak-dev/realms/moh_applications/clients/forms/main.tf
- keycloak-dev/realms/moh_applications/clients/hcimweb/main.tf
- keycloak-dev/realms/moh_applications/clients/moh-servicenow/main.tf
- keycloak-dev/realms/moh_applications/clients/pidp-webapp/main.tf
- keycloak-dev/realms/moh_applications/clients/prp-web/main.tf
Add PHSA username mapper to all DEV clients that use PHSA login.
Adds a client attribute mapper mapper that checks for the presence of a user attribute named phsa_windowsaccoutname, and, if it's present, it replaces preferred_username in the token.
A separate script will create the phsa_windowsaccoutname attribute on PHSA users.
According to my manual tests, this mapper will have no impact until the phsa_windowsaccountname exists.
Later, the IDP configuration will be updated to overwrite the existing Keycloak registration username with the UPN from PHSA.
The whole point of this is to allow applications that have already started using the "windowsaccountname" format to continue receiving it for existing users, while for new users they will receive the new UPN format.
> Add PHSA username mapper to all DEV clients that use PHSA login

- keycloak-test/realms/moh_applications/clients/usam/main.tf
Adding two redirect URLs for USAM client on test environment
> update USAM redirects

- keycloak-test/realms/moh_applications/clients/hcap-fe/main.tf
What is the context for those changes? For example: particular role needs to be shown in token. Reference Azure Board task, if applicable.
[^2]:
[^3]: Due to the terraform …
> Added /* to localhost redirect for local development

- keycloak-test/realms/moh_applications/clients/bcer-cp/main.tf
- keycloak-test/realms/moh_applications/clients/connect/main.tf
- keycloak-test/realms/moh_applications/clients/dht-dev/main.tf
- keycloak-test/realms/moh_applications/clients/forms/main.tf
- keycloak-test/realms/moh_applications/clients/gis/main.tf
- keycloak-test/realms/moh_applications/clients/hamis/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hiat1/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hiat2/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hiat3/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hs1/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_huat/main.tf
- keycloak-test/realms/moh_applications/clients/hscis/main.tf
- keycloak-test/realms/moh_applications/clients/hsiar/main.tf
- keycloak-test/realms/moh_applications/clients/hspp/main.tf
- keycloak-test/realms/moh_applications/clients/lra-dev/main.tf
- keycloak-test/realms/moh_applications/clients/miwt_stg/main.tf
- keycloak-test/realms/moh_applications/clients/moh-servicenow/main.tf
- keycloak-test/realms/moh_applications/clients/panorama/main.tf
- keycloak-test/realms/moh_applications/clients/pidp-webapp/main.tf
- keycloak-test/realms/moh_applications/clients/plr_iat/main.tf
- keycloak-test/realms/moh_applications/clients/plr_rev/main.tf
- keycloak-test/realms/moh_applications/clients/prp-web/main.tf
- keycloak-test/realms/moh_applications/clients/sat-eforms/main.tf
- keycloak-test/realms/moh_applications/clients/tbcm/main.tf
Add PHSA username mappers to all TEST clients that use PHSA login according to event logs.
RFC-20240429-01-BCMOHAD-20395-TEST-KEYCLOAK-Change_PHSA_Username_Format
[^2]:
> Add PHSA username mappers to all TEST clients that use PHSA login

- keycloak-test/realms/moh_applications/clients/bcer-cp/main.tf
- keycloak-test/realms/moh_applications/clients/connect/main.tf
- keycloak-test/realms/moh_applications/clients/dht-dev/main.tf
- keycloak-test/realms/moh_applications/clients/forms/main.tf
- keycloak-test/realms/moh_applications/clients/gis/main.tf
- keycloak-test/realms/moh_applications/clients/hamis/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hiat1/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hiat2/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hiat3/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hs1/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_huat/main.tf
- keycloak-test/realms/moh_applications/clients/hscis/main.tf
- keycloak-test/realms/moh_applications/clients/hsiar/main.tf
- keycloak-test/realms/moh_applications/clients/hspp/main.tf
- keycloak-test/realms/moh_applications/clients/lra-dev/main.tf
- keycloak-test/realms/moh_applications/clients/miwt_stg/main.tf
- keycloak-test/realms/moh_applications/clients/moh-servicenow/main.tf
- keycloak-test/realms/moh_applications/clients/panorama/main.tf
- keycloak-test/realms/moh_applications/clients/pidp-webapp/main.tf
- keycloak-test/realms/moh_applications/clients/plr_iat/main.tf
- keycloak-test/realms/moh_applications/clients/plr_rev/main.tf
- keycloak-test/realms/moh_applications/clients/prp-web/main.tf
- keycloak-test/realms/moh_applications/clients/sat-eforms/main.tf
- keycloak-test/realms/moh_applications/clients/tbcm/main.tf
I missed Panorama in the previous PR: https://github.com/bcgov/moh-keycloak-client-configurations/pull/519
> Add PHSA username mappers to all TEST clients that use PHSA login: Panorama

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/hides/main.tf
- keycloak-test/realms/moh_applications/clients/hides/outputs.tf
- keycloak-test/realms/moh_applications/clients/hides/versions.tf
Create HIDES client on Test environment.
Health Ideas Data Extraction Service, one of HealthIdeas applications. Same requirements and architecture as USAM application which is already integrated with Keycloak Test + Prod.
> create HIDES test client

- keycloak-dev/realms/moh_applications/clients.tf
- keycloak-dev/realms/moh_applications/clients/umc-e2e-tests/main.tf
- keycloak-dev/realms/moh_applications/clients/umc-e2e-tests/outputs.tf
- keycloak-dev/realms/moh_applications/clients/umc-e2e-tests/versions.tf
- keycloak-dev/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-dev/realms/moh_applications/clients/user-management/main.tf
Importing UMC-E2E client, roles and scopes to UMS/UMC.
Importing manually created client to terraform, so that E2E UMC tests won't break again. The client is just a role holder used in e2e tests. Roles are assigned to the testcafe user.
Plan should only show scope mapping changes, as rest of the resources was imported. (Plus some minor updates to client config)
> import umc-e2e client roles and scope to terraform

- keycloak-dev/realms/moh_applications/clients.tf
- keycloak-dev/realms/moh_applications/clients/phlat-service/main.tf
- keycloak-dev/realms/moh_applications/clients/phlat-service/outputs.tf
- keycloak-dev/realms/moh_applications/clients/phlat-service/variables.tf
- keycloak-dev/realms/moh_applications/clients/phlat-service/versions.tf
- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/phlat-service/main.tf
- keycloak-test/realms/moh_applications/clients/phlat-service/variables.tf
Creating PHLAT-SERVICE client on Keycloak dev.
Updating PHLAT-SERVICE client on Keycloak test.
Those clients are used to call PLR (Merge and CONF environments) with REG_ADMIN role.
> Configure phlat service client

- keycloak-test/realms/moh_applications/clients/icy/main.tf
- keycloak-test/realms/moh_applications/clients/maid/main.tf
- keycloak-test/realms/moh_applications/clients/sa-dbaac-portal/main.tf
- keycloak-test/realms/moh_applications/clients/sa-hibc-service-bc-portal/main.tf
- keycloak-test/realms/moh_applications/clients/sa-sfdc/main.tf
Adding URLs to CGI-managed Salesforce apps in Keycloak Test
Please find the client IDs for test environments:
For SATDevOrg: 
SA-SFDC
SA-HIBC-SERVICE-BC-PORTAL
SA-DBAAC-PORTAL
For SOSEUAT:
ICY
MAiD 
and URLs for test environments:
https://bchealth--satdevorg.sandbox.my.salesforce.com/
https://bcmohmaid--soseuat.sandbox.my.salesforce.com/
> add salesforce apps urls

- keycloak-test/realms/moh_applications/clients/hides/main.tf
Update URLs for HIDES application.
Client provided URLs with a typo and I did not notice.
> fix url typo

- keycloak-dev/realms/moh_applications/clients/bcer-cp/main.tf
- keycloak-dev/realms/moh_applications/clients/connect/main.tf
- keycloak-dev/realms/moh_applications/clients/forms/main.tf
- keycloak-dev/realms/moh_applications/clients/hcimweb/main.tf
- keycloak-dev/realms/moh_applications/clients/moh-servicenow/main.tf
- keycloak-dev/realms/moh_applications/clients/pidp-webapp/main.tf
- keycloak-dev/realms/moh_applications/clients/prp-web/main.tf
- keycloak-test/realms/moh_applications/clients/panorama/main.tf
Remove phsa_windowsaccoutname mappers on DEV.
Remove phsa_windowsaccoutname mappers on DEV. The mappers will later be recreated using a custom Override OIDC User Attribute Mapper. Note that this also removes the typo.
> Remove phsa_windowsaccoutname mappers on DEV.

- keycloak-dev/realms/moh_applications/clients/phlat-service/main.tf
- keycloak-test/realms/moh_applications/clients/phlat-service/main.tf
Add Client-ID mapper to the PHLAT service account in DEV and TEST.
PLR-ESB uses the client-id for some reason. Somewhere in the Keycloak 18 to 22 version upgrade, they changed the default from clientId to client_id to be spec compliant, so to use the old value we must manually specify it.
> Add Client-ID mapper to the PHLAT service account in DEV and TEST.

- keycloak-dev/realms/moh_applications/clients/forms/main.tf
Add the phsa_windowsaccountname to the FORMS DEV client using the new oidc-override-usermodel-attribute-mapper.
Part of the PHSA Entra ID username format change.
> Add the phsa_windowsaccountname to the FORMS DEV client using the new oidc-override-usermodel-attribute-mapper.

- keycloak-dev/realms/moh_applications/clients/bcer-cp/main.tf
- keycloak-dev/realms/moh_applications/clients/connect/main.tf
- keycloak-dev/realms/moh_applications/clients/forms/main.tf
- keycloak-dev/realms/moh_applications/clients/hcimweb/main.tf
- keycloak-dev/realms/moh_applications/clients/moh-servicenow/main.tf
- keycloak-dev/realms/moh_applications/clients/pidp-webapp/main.tf
- keycloak-dev/realms/moh_applications/clients/prp-web/main.tf
Add phsa_windowsaccountname mapper to all DEV clients with HA logins.
Part of the PHSA Entra ID integration epic.
> Add phsa_windowsaccountname mapper to all DEV clients with HA logins.

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/genesys/main.tf
- keycloak-test/realms/moh_applications/clients/genesys/outputs.tf
- keycloak-test/realms/moh_applications/clients/genesys/versions.tf
Importing GENESYS client to terraform. This SAML client was created manually and tested on Keycloak Test environment. 
This PR's goal is only to add terraform configuration code. 
Onboarding of Genesys to Keycloak.
The resources have been already imported to tf state file, so plan should not show any changes, apart from the hardcoded SAML attribute mapper - I made a typo when creating it manually so in Keycloak it's called "OrganizationName " instead of "OrganizationName". One mapper starts from the uppercase (OrganizationName) and other from lower case (email) -> that's what I've been given in the documentation by Genesys team.
> import genesys client to terraform

- keycloak-test/events.tf
Manage event configuration in TEST.
We continue to attempt to manage more and more Keycloak configuration using Terraform. Managing event configuration is a good step towards consistency across realms and audit compliance.
> Manage event configuration in TEST.

- keycloak-dev/events.tf
- keycloak-test/events.tf
Extend login event retention to three years in DEV and TEST.
OCIO information retention schedule compliance.
> Extend login event retention to three years in DEV and TEST.

- keycloak-test/realms/moh_applications/clients/bcer-cp/main.tf
- keycloak-test/realms/moh_applications/clients/connect/main.tf
- keycloak-test/realms/moh_applications/clients/dht-dev/main.tf
- keycloak-test/realms/moh_applications/clients/forms/main.tf
- keycloak-test/realms/moh_applications/clients/gis/main.tf
- keycloak-test/realms/moh_applications/clients/hamis/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hiat1/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hiat2/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hiat3/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hs1/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_huat/main.tf
- keycloak-test/realms/moh_applications/clients/hscis/main.tf
- keycloak-test/realms/moh_applications/clients/hsiar/main.tf
- keycloak-test/realms/moh_applications/clients/hspp/main.tf
- keycloak-test/realms/moh_applications/clients/lra-dev/main.tf
- keycloak-test/realms/moh_applications/clients/miwt_stg/main.tf
- keycloak-test/realms/moh_applications/clients/moh-servicenow/main.tf
- keycloak-test/realms/moh_applications/clients/panorama/main.tf
- keycloak-test/realms/moh_applications/clients/pidp-webapp/main.tf
- keycloak-test/realms/moh_applications/clients/plr_iat/main.tf
- keycloak-test/realms/moh_applications/clients/plr_rev/main.tf
- keycloak-test/realms/moh_applications/clients/prp-web/main.tf
- keycloak-test/realms/moh_applications/clients/sat-eforms/main.tf
- keycloak-test/realms/moh_applications/clients/tbcm/main.tf
TEST env: Add phsa_windowsaccountname to all clients that use HA login.
RFC-20240429-01-BCMOHAD-20395-TEST-KEYCLOAK-Change_PHSA_Username_Format
> TEST env: Add phsa_windowsaccountname to all clients that use HA login.

- keycloak-prod/realms/moh_applications/clients/user-management/main.tf
- keycloak-test/realms/moh_applications/clients/user-management/main.tf
Adding dmz1/dmz2 valid redirect URIs for UMC.
UMC doesn't have a `ROUTEID` cookie for us to switch instances.
[^1]:
> Adding dmz1/dmz2 valid redirect URIs for UMC

- keycloak-prod/realms/moh_applications/clients/webcaps/main.tf
- keycloak-test/events.tf
- keycloak-test/realms/moh_applications/clients/genesys/main.tf
Adding redirect URL for WEBCAPS. Enabling events logging in phsa realm.
Updating GENESYS URLs.
WEBCAPS changing servers - need to validate different envs.
Genesys client asked for the change so that user get's redirected to a subpage of an application (apps domain) instead of a welcome screen)
> add WEBCAPS redirect

- keycloak-test/realms/moh_applications/clients/panorama/main.tf
Remove Panorma PHSA username override mapper.
Panorama is not in PROD on Keycloak, so they can use the new format right from the start after doing a username migration. Fiona requests the default configuration.
> TEST: Remove Panorma PHSA username override mapper.

- keycloak-prod/events.tf
PROD: Enable login event logging in BCER realm.
I mistakenly labelled this as an IDP realm, and we don't log login events in IDP realms because it's redundant.
> PROD: Enable login event logging in BCER realm.

- keycloak-test/events.tf
Disable PHSA login event loggin in the TEST realm.
Login events are not recorded in IDP realms because it is mostly redundant as they already appear in moh_applications for real use. I enabled them for debugging purposes, which is no longer needed.
> Disable PHSA login event loggin in the TEST realm.

- keycloak-test/realms/moh_applications/clients/hcap-fe/main.tf
Adding two new development URLs to the valid redirects list
We are transitioning HCAP to CGI and don't have the ability to mask our URLs like they did
- [+] Valid Redirect URIs are properly defined, or explanation for `*` (allow all) is provided.
[^2]:
Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not interfere with existing configuration, they can be …
> adding local development URLs

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/genesys-training/main.tf
- keycloak-test/realms/moh_applications/clients/genesys-training/outputs.tf
- keycloak-test/realms/moh_applications/clients/genesys-training/versions.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hiat1/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hiat2/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hiat3/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hs1/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_hsit/main.tf
- keycloak-test/realms/moh_applications/clients/hcimweb_huat/main.tf
Creating GENESYS-TRAINING client on Keycloak Test env. Exact copy of GENESY client, with just one different organization parameter.
GENESYS client onboarding
> Create genesys test client

- keycloak-test/realms/moh_applications/clients/genesys-production/main.tf
- keycloak-test/realms/moh_applications/clients/genesys-training/main.tf
- keycloak-test/realms/moh_applications/clients/genesys/main.tf
Updating name of the Genesys Dev client. Add custom SAML attribute, which allows to skip the "splash" page and navigate user directly to "apps" page, improving user experience.
Feedback from the client after Genesys testing.
> add custom claim to genesys

- keycloak-dev/realms/moh_applications/clients/moh-servicenow/main.tf
- keycloak-prod/realms/moh_applications/clients/moh-servicenow/main.tf
- keycloak-test/realms/moh_applications/clients/moh-servicenow/main.tf
Rename "MoH ServiceNow" to "HLTH ServiceNow" as per Brad Allerton
"MoH" now refers to "Ministry of Housing" and not "Ministry of Health" within BC Gov. Previous references to "MoH" should now be "HLTH"
[^1]:
> Rename "MoH ServiceNow" to "HLTH ServiceNow" as per Brad Allerton

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/plr-iha/main.tf
- keycloak-test/realms/moh_applications/clients/plr-iha/outputs.tf
- keycloak-test/realms/moh_applications/clients/plr-iha/variables.tf
- keycloak-test/realms/moh_applications/clients/plr-iha/versions.tf
New service account that allows communication between PLR and IHA services.
PLR team request.
> create plr-iha service account

- keycloak-dev/realms/moh_applications/clients/user-management/main.tf
DEV env: Configuring idp-restriction module for UMC client via terraform.
Deploying idp-restriction-module to DEV env. Enabling idir_aad and moh_idp identity providers. Will need to update kc_idp_hint for UMC (part of separate task). After the change UMC should show common-logon page instead of redirecting to idp login page.
> configure idp-restriction for umc

- keycloak-dev/realms/moh_applications/clients/user-management/main.tf
Add missing default scopes.
Previous PR deleted the unspecified default scopes.
> add default scopes to UMC dev client

- keycloak-dev/realms/moh_applications/clientScopes.tf
Creating Client Scopes on DEV that represent IDPs. Those are later assigned to clients to allow use of IDP.
IDP Restriction module work.
> create idp-restriction-module client scopes

- keycloak-test/realms/moh_applications/clients/plr_conf/main.tf
- keycloak-test/realms/moh_applications/clients/plr_flvr/main.tf
- keycloak-test/realms/moh_applications/clients/plr_iat/main.tf
- keycloak-test/realms/moh_applications/clients/plr_rev/main.tf
- keycloak-test/realms/moh_applications/clients/plr_sit/main.tf
- keycloak-test/realms/moh_applications/clients/plr_stg/main.tf
- keycloak-test/realms/moh_applications/clients/plr_uat/main.tf
Service account is disabled for PLR_CONF, PLR_FLVR, PLR_IAT, PLR_REV, PLR_SIT, PLR_STG, PLR_UAT. The roles were also deleted from service account roles for these seven clients in test env. They do not exist in dev.
David S. asked for changes to PLR in dev and test for service account roles.
> disable service account option and delete service account roles

- keycloak-test/realms/moh_applications/clients/plr_conf/main.tf
- keycloak-test/realms/moh_applications/clients/plr_flvr/main.tf
- keycloak-test/realms/moh_applications/clients/plr_iat/main.tf
- keycloak-test/realms/moh_applications/clients/plr_rev/main.tf
- keycloak-test/realms/moh_applications/clients/plr_sit/main.tf
- keycloak-test/realms/moh_applications/clients/plr_stg/main.tf
- keycloak-test/realms/moh_applications/clients/plr_uat/main.tf
Removed the service account roles module from main.tf for PLR_CONF, PLR_FLVR, PLR_IAT, PLR_REV, PLR_SIT, PLR_STG and PLR_UAT in test env.
Changes previously made PR#599 caused terraform apply to fail due to "user not found" error. Fix found by David S. to apply.
> remove service account roles module from main.tf

- keycloak-test/realms/moh_applications/clients/sat-eforms/main.tf
- keycloak-test/realms/moh_applications/clients/sat-eforms_qa/main.tf
Added new attributes pidp_email and pidp_phone to SAT-EFORM and SAT-EFORM_QA in test env. Added to userinfo as well as added to access token.
Requested by client who had SA eforms needing email and phone number added to payload.
> add pidp email and phone to SAT-EFORM in test

- keycloak-prod/realms/moh_applications/clients/sat-eforms/main.tf
Added pidp_phone and pidp_email to SAT-EFORMS in prod env.
Changes requested by client to add phone and email attributes to SA eforms to their payload.
> add phone and email attributes to SAT-EFORMS in prod

- keycloak-dev/realms/moh_applications/clients.tf
- keycloak-dev/realms/moh_applications/clients/plr/main.tf
- keycloak-dev/realms/moh_applications/clients/plr/variables.tf
- modules/payara-client/main.tf
Override browser flow and theme for PLR client on DEV so that it uses the IDP restriction module.
Update payara-client module to allow overriding authentication(browser) flows.
IDP Restriction module work.
AuthenticationFlowBindingOverrides is an object, so unlike with primitive types a simple conditional expression cannot be used. Empty object would be created for each payara client that doesn't override authentication flow.
Instead, the solution uses `dynamic block` to conditionally assign this resource property. This ensures that only clients with `authentication_flow_binding_overrides` variable will undergo configuration change,
If `var.authentication_flow_binding_overrides` is not null, [1] triggers the dynamic block to create a single authentication_flow_binding_overrides block. [1] …
> Configure idp restriction module for plr

- keycloak-dev/realms/moh_applications/realm-roles/manage-users/main.tf
Add bulk-removal role to Manage-Users realm role.
On Keycloak DEV env, Manage-users is assigned to the am team and cgi dev team.
> update manage-users permissions

- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/phlat-service/main.tf
- keycloak-prod/realms/moh_applications/clients/phlat-service/outputs.tf
- keycloak-prod/realms/moh_applications/clients/phlat-service/variables.tf
- keycloak-prod/realms/moh_applications/clients/phlat-service/versions.tf
- keycloak-prod/realms/moh_applications/clients/phlat-web/main.tf
- keycloak-prod/realms/moh_applications/clients/phlat-web/outputs.tf
- keycloak-prod/realms/moh_applications/clients/phlat-web/versions.tf
- keycloak-prod/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-prod/realms/moh_applications/clients/user-management/main.tf
- keycloak-prod/realms/moh_applications/groups.tf
- keycloak-prod/realms/moh_applications/groups/phlat-management/main.tf
- keycloak-prod/realms/moh_applications/groups/phlat-management/output.tf
- keycloak-prod/realms/moh_applications/groups/phlat-management/variables.tf
- keycloak-prod/realms/moh_applications/groups/phlat-management/versions.tf
- keycloak-prod/realms/moh_applications/realm-roles/manage-users/main.tf
Promoting PHLAT clients to Production. Changes include:
- Create PHLAT-WEB client. Public client with default access token lifespan.
- Create PHLAT-SERVICE client. Service account used to communicate with PLR.
- Create PHLAT-MANAGEMENT group so users' access can be managed through UMC.
- Update UMC and UMS config to include view-client-phlat-web role
- Update ManageUsers realm role.
Client onboarding PHLAT is moving to Production.
> promote phlat to production

- keycloak-prod/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-prod/realms/moh_applications/clients/user-management/main.tf
- keycloak-prod/realms/moh_applications/groups.tf
- keycloak-prod/realms/moh_applications/groups/edrd-management/main.tf
- keycloak-prod/realms/moh_applications/groups/edrd-management/output.tf
- keycloak-prod/realms/moh_applications/groups/edrd-management/variables.tf
- keycloak-prod/realms/moh_applications/groups/edrd-management/versions.tf
Adding EDRD-Management group on Prod, so that roles can be assigned through UMC.
EDRD client onboarding. This group may be temporary - depending on who will be admin team once they fully cut over.
> create edrd-management group

- keycloak-dev/realms/moh_applications/clients.tf
- keycloak-dev/realms/moh_applications/clients/bulk-user-upload/main.tf
- keycloak-dev/realms/moh_applications/clients/bulk-user-upload/outputs.tf
- keycloak-dev/realms/moh_applications/clients/bulk-user-upload/variables.tf
- keycloak-dev/realms/moh_applications/clients/bulk-user-upload/versions.tf
- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/bulk-user-upload/main.tf
- keycloak-prod/realms/moh_applications/clients/bulk-user-upload/outputs.tf
- keycloak-prod/realms/moh_applications/clients/bulk-user-upload/variables.tf
- keycloak-prod/realms/moh_applications/clients/bulk-user-upload/versions.tf
- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/bulk-user-upload/main.tf
- keycloak-test/realms/moh_applications/clients/bulk-user-upload/outputs.tf
- keycloak-test/realms/moh_applications/clients/bulk-user-upload/variables.tf
- keycloak-test/realms/moh_applications/clients/bulk-user-upload/versions.tf
Creating bulk-upload clients on dev/test/prod. The clients are disabled by default.
Clients (their service accounts) are used to perform bulk user upload and role assignment to Keycloak. Previously, the script was using a plain user to execute the script via admin-cli. 
Before applying, the client on dev needs to be deleted.
> create bulk-upload clients

- keycloak-prod/realms/moh_applications/groups/cgi-registries-admin/main.tf
- keycloak-prod/realms/moh_applications/groups/cgi-salesforce/main.tf
- keycloak-test/realms/moh_applications/groups/cgi-registries-admin/main.tf
- keycloak-test/realms/moh_applications/groups/cgi-salesforce/main.tf
Remove manage-own-groups from multiple CGI Groups.
Group management for CGI groups must be managed by access requests on JIRA with client approval.
> Remove manage-own-groups from multiple CGI Groups.

- keycloak-test/realms/moh_applications/clientScopes.tf
Creating client scopes that represent idp-aliases on Keyclok test environment.
The scopes will be used as a part of the IDP restriction module.
> create idp-alias scopes

- keycloak-dev/events.tf
Cleaning up realm events  config on dev
`pidpsandbox` and `bcproviderlab` realms have been removed from the DEV environment.
> cleanup dev events config

- keycloak-dev/realms/moh_applications/clients.tf
- keycloak-dev/realms/moh_applications/clients/user-management/main.tf
- keycloak-dev/realms/moh_applications/clients/user-management/variables.tf
- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/prp-service/main.tf
- keycloak-test/realms/moh_applications/clients/prp-web/main.tf
- keycloak-test/realms/moh_applications/clients/user-management/main.tf
- keycloak-test/realms/moh_applications/clients/user-management/variables.tf
Add 3 new PRP roles on TEST. Configure idp-restriction-module on Keycloak TEST environment. Replacing hardcoded browser-flow id with a variable.
> add prp roles and configure idp restriction module

- keycloak-test/realms/moh_applications/groups/registries-connections-team/main.tf
Assigning bulk-removal permissions to the Registries-Connections Team in Test environment.
> add bulk-removal permissions to registries team

- keycloak-test/realms/moh_citizen/clients/emaccs/main.tf
Adding SYSADMIN role to emaccs in test.
Requested by Adam H.
> add sysadmin role to emaccs in test

- keycloak-prod/realms/moh_applications/clients/bcer-cp/main.tf
- keycloak-test/realms/moh_applications/clients/bcer-cp/main.tf
adding two url redirects to test bcer client https://bcer-dev.s3.amazonaws.com
https://bcer-test.s3.amazonaws.com and one url redirect to prod bcer client https://bcer-prod.s3.amazonaws.com
> add url redirects to test and prod for bcer

- keycloak-test/realms/moh_citizen/clients/emaccs/main.tf
Adding CA, CCA, DIRECTOR and READONLY roles to EMACCS client in test.
Requested by Adam H.
> add roles to emaccs in test

- keycloak-test/realms/moh_citizen/clients/emaccs/main.tf
Update EMACCS role descriptions to match what was previously in LDAPAdmin.
Changes related to EMACCS client on-boarding.
[^1]:
> Update EMACCS role descriptions to match what was previously in LDAPAdmin

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/emaccs-ums/main.tf
- keycloak-test/realms/moh_applications/clients/emaccs-ums/outputs.tf
- keycloak-test/realms/moh_applications/clients/emaccs-ums/variables.tf
- keycloak-test/realms/moh_applications/clients/emaccs-ums/versions.tf
Creating EMACCS-UMS client, a service account that will allow EMACCS to call UMS API. 
Flow: EMACCS-UMS obtains token from moh_applications realm, passes it in a request to UMS API that fetches data from moh_citizen.
EMACCS client onboarding.
> emaccs-ums service account

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/florizel/main.tf
- keycloak-test/realms/moh_applications/clients/florizel/outputs.tf
- keycloak-test/realms/moh_applications/clients/florizel/versions.tf
Importing FLORIZEL client to Keycloak test environment.
Terraform plan should show 3 additions - new roles. Rest of the resources were imported.
> import florizel test client

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/florizel-training/main.tf
- keycloak-test/realms/moh_applications/clients/florizel-training/outputs.tf
- keycloak-test/realms/moh_applications/clients/florizel-training/versions.tf
Creating Florizel-Training client. Copy of Florizel, but with different home and ACS URLs.
Florizel client onboarding
> create florizel-training client

- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/florizel/main.tf
- keycloak-prod/realms/moh_applications/clients/florizel/outputs.tf
- keycloak-prod/realms/moh_applications/clients/florizel/versions.tf
- keycloak-prod/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-prod/realms/moh_applications/clients/user-management/main.tf
- keycloak-test/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-test/realms/moh_applications/clients/user-management/main.tf
Promote Florizel to Prod. Enable Florizel roles assignment  through UMC in Test and Production
Florizel client onboarding
[^2]:
> promote florizel to prod

- keycloak-test/realms/moh_applications/clients/hsiar/main.tf
- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding new identity_provider claim to hspp and hsiar in test env. claim already exists in prp web.
Change requested by client.
> adding new IDP claim to hspp and hsiar in test

- keycloak-dev/realms/moh_applications/clientScopes.tf
Add a `yukon_aad` scope to the `moh_applications` realm in DEV for use by the IDP restriction module.
This scope may be used by any client in conjunction with the IDP restriction module to restrict that client to using specific IDPs for login.
> Create Yukon AAD scope in DEV for IDP restriction module use.

- keycloak-test/realms/moh_applications/clientScopes.tf
Adding yukon_aad scope to moh_applications realm in test for use of IDP restriction module.
This scope may be used by any client in conjunction with the IDP restriction module to restrict that client to using specific IDPs for login. Test environment.
> adding yukon aad scope in test for IDP restriction moduel

- keycloak-prod/realms/moh_applications/clients.tf
- keycloak-prod/realms/moh_applications/clients/hsiar/main.tf
- keycloak-prod/realms/moh_applications/clients/hsiar/variables.tf
- keycloak-prod/realms/moh_applications/clients/hspp/main.tf
- keycloak-prod/realms/moh_applications/clients/hspp/variables.tf
- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/hsiar/main.tf
- keycloak-test/realms/moh_applications/clients/hsiar/variables.tf
- keycloak-test/realms/moh_applications/clients/hspp/main.tf
- keycloak-test/realms/moh_applications/clients/hspp/variables.tf
Adding license status and identity provider claim to hspp and hsiar to test and prod environment. Also adding license status roles.
Changes requested by client. Also for PRP - this seems to exist already.
> adding license status and identity provider claim to hspp and hsiar

- keycloak-prod/realms/moh_applications/groups/florizel-management/main.tf
- keycloak-test/realms/moh_applications/groups/florizel-management/main.tf
Allowing FLORIZEL admins to pre-register users.
> update florizel admin permissions

- keycloak-dev/realms/moh_applications/clientScopes.tf
- keycloak-prod/realms/moh_applications/clientScopes.tf
- keycloak-test/realms/moh_applications/clientScopes.tf
- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/florizel/main.tf
- keycloak-test/realms/moh_applications/clients/florizel/variables.tf
- keycloak-test/realms/moh_applications/clients/genesys/main.tf
- keycloak-test/realms/moh_applications/clients/genesys/variables.tf
Setting up IDP restriction module for Genesys and Florizel test clients.
Enforcing IDIR MFA in test realm
> introduce idp restriction module to genesys and florizel

- keycloak-prod/realms/moh_applications/clients/hsiar/main.tf
- keycloak-prod/realms/moh_applications/clients/hspp/main.tf
- keycloak-prod/realms/moh_applications/clients/prp-web/main.tf
- keycloak-test/realms/moh_applications/clients/hsiar/main.tf
- keycloak-test/realms/moh_applications/clients/prp-web/main.tf
Adding idir_mailboxOrgCode and idir_displayName attributes to prod and test for PRP-WEB, HSIAR and HSPP clients.
Note: these attributes already existed in HSPP test.
> adding attributes to prp hsiar hspp prod and test

- keycloak-dev/realms/moh_applications/clients/prp-web/main.tf
- keycloak-test/realms/moh_applications/clients/hsiar/main.tf
- keycloak-test/realms/moh_applications/clients/hspp/main.tf
- keycloak-test/realms/moh_applications/clients/prp-web/main.tf
Removing phsa_windowsaccountname mapper from PRP-WEB in dev. PRP-WEB, HSIAR, HSPP in test.
> removing phsa windows account name mapper

- keycloak-prod/realms/moh_applications/clients/hspp/main.tf
- keycloak-prod/realms/moh_applications/clients/prp-web/main.tf
Removing old phsa windows account mapper from prod for HSPP and PRP-WEB. *Did not exist for HSIAR.
Requested by client.
> removing phsa windows account mapper from prod hspp/prp

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/alr/main.tf
- keycloak-test/realms/moh_applications/clients/alr/variables.tf
- keycloak-test/realms/moh_applications/clients/edrd-portal/main.tf
- keycloak-test/realms/moh_applications/clients/edrd-portal/variables.tf
- keycloak-test/realms/moh_applications/clients/edrd/main.tf
- keycloak-test/realms/moh_applications/clients/edrd/variables.tf
- keycloak-test/realms/moh_applications/clients/icy/main.tf
- keycloak-test/realms/moh_applications/clients/icy/variables.tf
- keycloak-test/realms/moh_applications/clients/maid/main.tf
- keycloak-test/realms/moh_applications/clients/maid/variables.tf
- keycloak-test/realms/moh_applications/clients/sa-dbaac-portal/main.tf
- keycloak-test/realms/moh_applications/clients/sa-dbaac-portal/variables.tf
- keycloak-test/realms/moh_applications/clients/sa-hibc-service-bc-portal/main.tf
- keycloak-test/realms/moh_applications/clients/sa-hibc-service-bc-portal/variables.tf
- keycloak-test/realms/moh_applications/clients/sa-sfdc/main.tf
- keycloak-test/realms/moh_applications/clients/sa-sfdc/variables.tf
- keycloak-test/realms/moh_applications/clients/tpl/main.tf
- keycloak-test/realms/moh_applications/clients/tpl/variables.tf
Enforcing IDIR MFA for CGI-Salesforce applications in Keycloak Test. Omitted PRIMARY-CARE for now. 
Enforcing by configuring the idp restriction module. Idps in use were deducted based on the CMDB and visiting applications in Keycloak Tes environment.
> Idp restriction module test

- keycloak-prod/realms/moh_applications/clients/hspp/main.tf
- keycloak-test/realms/moh_applications/clients/hspp/main.tf
Adding 6 new roles to HSPP in test and prod environment.
1.	HSPP_ReportProgram_Operations 
2.	HSPP_ReportSection_Operations 
3.	HSPP_Operations_PPM_PPD 
4.	HSPP_Operations_CCS_PA 
5.	HSPP_Operations_CCS_SDA 
6.	HSPP_Operations_PAW_HA 
> adding new roles to hspp test and prod

- keycloak-dev/realms/moh_applications/clients/bcer-cp/main.tf
- keycloak-dev/realms/moh_applications/clients/connect/main.tf
- keycloak-dev/realms/moh_applications/clients/forms/main.tf
- keycloak-dev/realms/moh_applications/clients/hcimweb/main.tf
- keycloak-dev/realms/moh_applications/clients/moh-servicenow/main.tf
- keycloak-dev/realms/moh_applications/clients/pidp-webapp/main.tf
Updating custom mappers on DEV to include the introspection.toke.claim value.
Introspection token endpoint is not available in Keycloak, so we do not need to make those mappers available.
> update introspection token claims

- keycloak-test/realms/moh_applications/clients/hcap-fe/main.tf
- keycloak-test/realms/moh_applications/clients/mspdirect-web-uat/main.tf
- keycloak-test/realms/moh_applications/clients/mspdirect-web/main.tf
MSP-DIRECT test: Add logout URLs to valid redirects. Restricted allowed web-origins for best practice.
The MSP-DIRECT team requested our assistance fixing IDIR logout. I also restricted web-origins because it shouldn't be `*`.
> MSP-DIRECT test: Add logout URLs to valid redirects. 

- keycloak-dev/realms/moh_applications/clients/prime-application-dev/main.tf
- keycloak-dev/realms/moh_applications/clients/prime-application-local/main.tf
- keycloak-dev/realms/moh_applications/clients/prime-application-test/main.tf
- keycloak-prod/realms/moh_applications/clients/terraform/main.tf
- keycloak-test/realms/moh_applications/clients/prime-application-dev/main.tf
- keycloak-test/realms/moh_applications/clients/prime-application-local/main.tf
- keycloak-test/realms/moh_applications/clients/prime-application-test/main.tf
DEV/TEST: Adding default scopes to PRIME client address scope default.
Fix missing address scope setting in PRIME Terraform config
Adds the address scope to the client default scopes in PRIME’s Terraform config to match the manual changes already applied in DEV, TEST, and PROD. This ensures consistency and avoids future issues when reusing the configuration.
> DEV/TEST: Adding default scopes to PRIME clients.

- keycloak-test/realms/moh_applications/clients/prime-application-dev/main.tf
- keycloak-test/realms/moh_applications/clients/prime-application-local/main.tf
- keycloak-test/realms/moh_applications/clients/prime-application-test/main.tf
TEST: Add basic scope to PRIME clients.
Accidentally removed basic scope with recent change. Client is no longer receiving "sub" claim.
> TEST: Add basic scope to PRIME clients.

- keycloak-test/realms/moh_applications/clients.tf
- keycloak-test/realms/moh_applications/clients/ivf-clinic-portal/main.tf
- keycloak-test/realms/moh_applications/clients/ivf-clinic-portal/outputs.tf
- keycloak-test/realms/moh_applications/clients/ivf-clinic-portal/variables.tf
- keycloak-test/realms/moh_applications/clients/ivf-clinic-portal/versions.tf
- keycloak-test/realms/moh_applications/clients/user-management-service/main.tf
- keycloak-test/realms/moh_applications/clients/user-management/main.tf
- keycloak-test/realms/moh_applications/groups/ivf-portal-management/main.tf
Create a new IVF-CLINIC-PORTAL client. Update IVF-PORTAL.
Finalized requirements during client meeting.
[^2]:
[^3]: Due to the terraform provider bug, updating/deleting one entry within the resource deletes all of them. …
> create ivf-clinic portal

- keycloak-test/realms/moh_applications/clients/hdpbc/main.tf
- keycloak-test/realms/moh_applications/clients/metaspace/main.tf
Add backwards compatiblity mapper "session_state" to METASPACE and HDPBC clients in TEST.
Requested by clients for BCMOHAM-24567
> Add backwards compatiblity mapper "session_state" to METASPACE and HDPBC clients in TEST
